// acid_bass.cc -- "Acid Bass", a monophonic bass after the TB-303: the 303
// bass of fm1-x0x (Charles Vestal, GPL-3.0-only), vendored with two small
// local changes in third_party/fm1-x0x/ (UPSTREAM.md), behind engine API v3.
// It links GPL code, so it is built only while the GPL switch is on
// (FM1_GPL_MODS, engines/Makefile; mk/fm1-x0x.mk) and listed GPL in the
// licence table (src/registry.cc).
//
// What fm1-x0x's bass is (third_party/fm1-x0x/dsp/bass303.h has the detail):
// Open303's signal path by Robin Schmidt (MIT), statement for statement, with
// a polyBLEP saw and the 303's tanh-shaped square, 2x oversampling, controls
// every 4 samples, the Devilfish ranges for slide and accent decay after
// jc303 (midilab, GPL-3.0), and a Soft or RAT drive after schwung-303's (the
// RAT after dm-Rat, Dave Mollen, GPL-3.0). schwung-303 (Charles Vestal) is
// the port it came through. Every instance is self-contained.
//
// What this file adds, and how it plays (engines/README.md, "Acid Bass"):
//   - Notes, as Open303's MIDI handling and schwung-303 play them. A key
//     list, newest last (16 keys). A note-on with no key held triggers the
//     note; one played while another is held slides to it without
//     restarting the envelopes (legato is the 303's slide), at the Slide
//     time. Letting go of the newest key while older ones are held slides
//     back to the newest of them; letting go of the last releases. A
//     velocity of 100 or more is an accent (schwung-303's rule, which
//     TB-3PO's 118 and 72 meet); velocity does nothing else, as on the 303.
//   - The rate: the host's own, 40-96 kHz (the vendored bass reads the
//     instance's rate where upstream reads 44,100; at 44.1 kHz it computes
//     upstream's samples). Hosts outside that are refused.
//   - A grid of 16 samples. The vendored bass's output depends on where
//     its render calls split, so it renders whole 16-sample chunks, counted
//     from create, and the host's frames are handed out of the last chunk.
//     A note, a bend or a parameter lands on the next chunk (0.36 ms at
//     44,118 Hz), so the output is the same at any host block size and any
//     split of a block. A chunk is the control block of the SMOOTH ramps.
//   - Parameters in their own units (Hz, %, ms), as floats, not 7-bit pots:
//     each reaches the vendored bass as a pot position between the integers
//     (bass303_set_value, a local change). The mapping is X0X's: Cutoff
//     314-2,394 Hz and Decay 200-2,000 ms exponential, Slide 2-360 ms and
//     Acc Decay 30-3,000 ms linear in the pot.
//   - Pitch outside the vendored bass: Tune, the bend and the voice's
//     per-note pitch offset multiply the oscillator's target and its slewed
//     frequency alike, so a bend moves the note at once and a slide in
//     progress goes on from where it is. With all three at 0 nothing is
//     multiplied: the vendored bass's own pitch, bit for bit.
//   - Volume outside it too: the vendored bass keeps X0X's default level
//     (its Volume pot at 96, -14.6 dB, so the drive sees the level X0X
//     tuned it at), and Volume scales its output by (Volume / 0.7)^2, so the
//     default, 0.7, is X0X's output exactly and 1 is 6.2 dB louder.
//   - Flags. Cutoff, Resonance, Env Mod, Tune, Volume, Drive and Slide are
//     read continuously: SMOOTH (a ramp over 2.5 ms, 7 chunks at 44,118 Hz,
//     while a note sounds) and MOD; Cutoff and Slide LOG. Decay, Accent and
//     Acc Decay are read at a note-on, slides included, as in Open303:
//     LATCH. Wave and Drive Type would click mid-note, so they wait for the
//     next note that is not a slide (LATCH and MOD: a route is rounded);
//     while nothing sounds they apply at once. Cutoff, Resonance, Env Mod,
//     Drive and Volume are POLY: the voice keeps an offset for each, and one
//     for its pitch, which restart at 0 whenever it moves to another key
//     (a trigger, a slide or a slide back) and end with it.
//
// No allocation and no libm: the vendored bass has its own maths
// (fastmath.h), and the wrapper's exp2 and log2 are fm1_math.h's, so every
// build computes the same bits.
//
// MIT licence (this file); the program it is linked into is GPL-3.0 while
// the vendored bass is in it.

#include "fm1_engine.h"
#include "fm1_gpl_mods.h"   // FM1_GPL_MODS, generated by engines/Makefile
#include "fm1_math.h"
#include "fm1_smooth.h"

#if !FM1_GPL_MODS
#error "acid_bass.cc links GPL code: it is built only with FM1_GPL_MODS=1 (engines/mk/fm1-x0x.mk)"
#endif

extern "C" {
#include "dsp/bass303.h"
#include "dsp/fastmath.h"
}

#include <new>

#include "acid_bass.h"

namespace fm1 {
namespace acid_bass {

enum Param {
  P_CUTOFF, P_RESO, P_ENVMOD, P_DECAY,        // page 1: the filter
  P_ACCENT, P_WAVE, P_TUNE, P_VOLUME,         // page 2: the voice
  P_DRIVE, P_DRVTYPE, P_SLIDE, P_ACCDEC,      // page 3: drive and the Devilfish ranges
  P_COUNT
};
// X0X's own order (bass303.h's BASS303_*), so an index is the vendored one.
typedef char order_matches[P_CUTOFF == BASS303_CUTOFF && P_RESO == BASS303_RESO &&
                           P_ENVMOD == BASS303_ENVMOD && P_DECAY == BASS303_DECAY &&
                           P_ACCENT == BASS303_ACCENT && P_WAVE == BASS303_WAVE &&
                           P_TUNE == BASS303_TUNE && P_VOLUME == BASS303_VOLUME &&
                           P_DRIVE == BASS303_DRIVE && P_DRVTYPE == BASS303_DRVTYPE &&
                           P_SLIDE == BASS303_SLIDE && P_ACCDEC == BASS303_ACCDEC &&
                           P_COUNT == BASS303_NPARAMS ? 1 : -1];

const char *const kWaveNames[] = { "Saw", "Square" };
const char *const kDriveNames[] = { "Off", "Soft", "RAT" };

const uint16_t kCont = FM1_PARAM_CONTINUOUS;
const uint16_t kContPoly = FM1_PARAM_CONTINUOUS | FM1_PARAM_POLY;
const uint16_t kContLogPoly = FM1_PARAM_CONTINUOUS_LOG | FM1_PARAM_POLY;
const uint16_t kLatch = FM1_PARAM_LATCH | FM1_PARAM_MOD;
const uint16_t kLatchLog = FM1_PARAM_LATCH | FM1_PARAM_MOD | FM1_PARAM_LOG;

// Uids (API v2) are fixed: never renumber one; a new parameter takes the next
// free uid. Defaults: schwung-303's knobs at their middles, rounded (X0X's pot
// 64 is 874 Hz, 50.4 % and 638 ms), and Slide and Acc Decay at the stock
// 303's 60 and 200 ms, which X0X's pots can only come near (61 and 194).
const fm1_param_t kParams[P_COUNT] = {
  { "Cutoff",     FM1_PARAM_FLOAT, 314, 2394, 870, NULL, 0, 1, kContLogPoly, FM1_UNIT_HZ, "Cut" },
  { "Resonance",  FM1_PARAM_FLOAT, 0, 100, 50, NULL, 0, 2, kContPoly, FM1_UNIT_PCT, "Res" },
  { "Env Mod",    FM1_PARAM_FLOAT, 0, 100, 50, NULL, 0, 3, kContPoly, FM1_UNIT_PCT, "EnvMod" },
  { "Decay",      FM1_PARAM_FLOAT, 200, 2000, 630, NULL, 0, 4, kLatchLog, FM1_UNIT_MS, "Decay" },
  { "Accent",     FM1_PARAM_FLOAT, 0, 100, 50, NULL, 1, 5, kLatch, FM1_UNIT_PCT, "Accent" },
  { "Wave",       FM1_PARAM_ENUM, 0, 1, 0, kWaveNames, 1, 6, kLatch, FM1_UNIT_NONE, "Wave" },
  { "Tune",       FM1_PARAM_FLOAT, -12, 12, 0, NULL, 1, 7, kCont, FM1_UNIT_SEMI, "Tune" },
  { "Volume",     FM1_PARAM_FLOAT, 0, 1, 0.7f, NULL, 1, 8, kContPoly, FM1_UNIT_NONE, "Vol" },
  { "Drive",      FM1_PARAM_FLOAT, 0, 100, 0, NULL, 2, 9, kContPoly, FM1_UNIT_PCT, "Drive" },
  { "Drive Type", FM1_PARAM_ENUM, 0, 2, 1, kDriveNames, 2, 10, kLatch, FM1_UNIT_NONE, "DrvTyp" },
  { "Slide",      FM1_PARAM_FLOAT, 2, 360, 60, NULL, 2, 11, FM1_PARAM_CONTINUOUS_LOG, FM1_UNIT_MS, "Slide" },
  { "Acc Decay",  FM1_PARAM_FLOAT, 30, 3000, 200, NULL, 2, 12, kLatchLog, FM1_UNIT_MS, "AccDec" },
};

const int kMaxKeys = 16;
const float kVolumeRef = 0.7f;        // Volume at which the output is X0X's
const int kX0xVolumePot = 96;         // X0X's own default level, kept inside
const int kX0xTunePot = 64;           // A4 = 440 Hz: pitch is the wrapper's

inline float Clamp(float v, float lo, float hi) { return v < lo ? lo : (v > hi ? hi : v); }

// The pot position (0..127, a float) for parameter i at value v, in X0X's
// mapping (bass303.c, bass303_set); see acid_bass.h for the inverse.
float PotOf(int i, float v) {
  switch (i) {
    case P_CUTOFF: return 127.0f * (fm1_log2f(v * (1.0f / 314.0f)) * (1.0f / 2.930586688f));
    case P_DECAY: return 127.0f * (fm1_log2f(v * (1.0f / 200.0f)) * (1.0f / 3.321928095f));
    case P_SLIDE: return 127.0f * ((v - 2.0f) * (1.0f / 358.0f));
    case P_ACCDEC: return 127.0f * ((v - 30.0f) * (1.0f / 2970.0f));
    default: return v * 1.27f;        // the percentages
  }
}

struct Instance {
  bass303_t unit;                     // fm1-x0x's bass, first: 16-byte aligned
  float value[P_COUNT];               // set_param's values, the base
  float cur[P_COUNT];                 // the ramped base the voice plays
  fm1_smooth_t ramp[P_COUNT];
  float offset[P_COUNT];              // the voice's per-note offsets (POLY only)
  float applied[P_COUNT];             // what the unit was last given, per parameter
  float note_pitch;                   // the voice's per-note pitch offset, semitones
  float bend;                         // semitones
  float mult;                         // the pitch multiplier the unit's frequencies carry
  float base_hz;                      // the sounding key's frequency at A4 = 440 Hz
  float gain;                         // the chunk's output gain
  float rate;
  float buf[kChunk];
  uint32_t pos;                       // next sample of buf to hand out; kChunk: empty
  uint32_t steps;                     // ramp length in chunks
  uint8_t keys[kMaxKeys];             // held keys, oldest first
  uint8_t vels[kMaxKeys];
  int n_keys;
  int sounding;                       // the key the voice plays, or -1
  int wave, drive_type;               // what the unit plays now
  uint8_t pad[8];

  bool Init(const fm1_host_t *host) {
    const float r = host ? host->sample_rate : 0.0f;
    if (!(r >= kMinRate && r <= kMaxRate)) return false;
    rate = r;
    bass303_init_rate(&unit, rate);
    bass303_set(&unit, BASS303_TUNE, kX0xTunePot);
    bass303_set(&unit, BASS303_VOLUME, kX0xVolumePot);
    for (int i = 0; i < P_COUNT; ++i) {
      value[i] = cur[i] = kParams[i].def;
      offset[i] = 0.0f;
      applied[i] = -1.0f;             // below every range: the first Apply sets all
    }
    fm1_smooth_init(ramp, value, P_COUNT);
    wave = static_cast<int>(kParams[P_WAVE].def);
    drive_type = static_cast<int>(kParams[P_DRVTYPE].def);
    bass303_set(&unit, BASS303_WAVE, wave);
    bass303_set(&unit, BASS303_DRVTYPE, drive_type);
    note_pitch = bend = 0.0f;
    mult = 1.0f;
    base_hz = unit.osc_freq;
    gain = 1.0f;
    for (uint32_t k = 0; k < kChunk; ++k) buf[k] = 0.0f;
    pos = kChunk;
    steps = fm1_smooth_steps(rate, kChunk);
    for (int k = 0; k < kMaxKeys; ++k) keys[k] = vels[k] = 0;
    n_keys = 0;
    sounding = -1;
    for (int k = 0; k < 8; ++k) pad[k] = 0;
    Apply();
    return true;
  }

  bool Silent() const { return unit.idle != 0; }

  // The value the voice plays for parameter i: its ramped base, plus its
  // offset when it is POLY, clamped as set_param clamps.
  float Effective(int i) const {
    if (!(kParams[i].flags & FM1_PARAM_POLY) || offset[i] == 0.0f) return cur[i];
    return fm1_param_note_value(&kParams[i], cur[i], offset[i]);
  }

  // Every parameter the unit holds itself, given to it when it changed.
  void Apply() {
    static const int kUnit[] = { P_CUTOFF, P_RESO, P_ENVMOD, P_DECAY, P_ACCENT, P_DRIVE, P_SLIDE,
                                 P_ACCDEC };
    for (unsigned k = 0; k < sizeof(kUnit) / sizeof(kUnit[0]); ++k) {
      const int i = kUnit[k];
      const float v = Effective(i);
      if (v == applied[i]) continue;
      applied[i] = v;
      bass303_set_value(&unit, i, PotOf(i, v));
    }
    {
      const float r = Effective(P_VOLUME) / kVolumeRef;
      gain = r * r;
    }
  }

  // The switches wait for a note that starts the voice, or for silence.
  void ApplySwitches() {
    const int w = static_cast<int>(cur[P_WAVE] + 0.5f);
    const int d = static_cast<int>(cur[P_DRVTYPE] + 0.5f);
    if (w != wave) {
      wave = w;
      bass303_set(&unit, BASS303_WAVE, w);
    }
    if (d != drive_type) {
      drive_type = d;
      bass303_set(&unit, BASS303_DRVTYPE, d);
    }
  }

  // Tune, the bend and the per-note pitch: one multiplier on the unit's
  // target and slewed frequencies. 1 multiplies nothing.
  void ApplyPitch() {
    const float semis = Effective(P_TUNE) + bend + note_pitch;
    float m = 1.0f;
    if (semis != 0.0f) m = fm1_exp2f(semis * (1.0f / 12.0f));
    if (m == mult) return;
    unit.osc_freq = m == 1.0f ? base_hz : base_hz * m;
    unit.slew_y = unit.slew_y / mult;
    unit.slew_y = unit.slew_y * m;
    mult = m;
  }

  // A key's frequency as the unit computes it for a note-on (bass303.c).
  float KeyHz(int key) const {
    return unit.tuning * fm_exp2f(static_cast<float>(key - 69) * (1.0f / 12.0f));
  }

  // The voice moves to another key: its offsets start again at 0.
  void NewKey(int key) {
    sounding = key;
    for (int i = 0; i < P_COUNT; ++i) offset[i] = 0.0f;
    note_pitch = 0.0f;
  }

  void Chunk() {
    if (fm1_smooth_moving(ramp, P_COUNT)) fm1_smooth_tick(ramp, cur, P_COUNT);
    Apply();
    ApplyPitch();
    if (Silent()) ApplySwitches();
    bass303_render(&unit, buf, static_cast<int>(kChunk));
    if (gain != 1.0f) {
      for (uint32_t k = 0; k < kChunk; ++k) buf[k] = buf[k] * gain;
    }
    if (Silent() && sounding >= 0) NewKey(-1);   // the voice has ended
    pos = 0;
  }

  void Render(float *out, uint32_t frames) {
    uint32_t done = 0;
    while (done < frames) {
      if (pos == kChunk) Chunk();
      uint32_t n = kChunk - pos;
      if (n > frames - done) n = frames - done;
      for (uint32_t k = 0; k < n; ++k) {
        const float v = buf[pos + k];
        out[2 * (done + k)] = v;
        out[2 * (done + k) + 1] = v;
      }
      pos += n;
      done += n;
    }
  }

  void Remove(int key) {
    int w = 0;
    for (int k = 0; k < n_keys; ++k) {
      if (keys[k] == key) continue;
      keys[w] = keys[k];
      vels[w] = vels[k];
      ++w;
    }
    n_keys = w;
  }

  void NoteOn(uint8_t key, uint8_t velocity) {
    if (key > 127) return;
    if (velocity == 0) {
      NoteOff(key);
      return;
    }
    Remove(key);
    const bool slide = n_keys > 0 && unit.gate;
    if (n_keys == kMaxKeys) {                  // full: the oldest goes
      for (int k = 1; k < n_keys; ++k) {
        keys[k - 1] = keys[k];
        vels[k - 1] = vels[k];
      }
      --n_keys;
    }
    keys[n_keys] = key;
    vels[n_keys] = velocity;
    ++n_keys;
    NewKey(key);
    if (!slide) {
      ApplySwitches();
      Apply();                                 // the offsets just went
    }
    bass303_note_on(&unit, key, velocity >= 100, slide ? 1 : 0);
    base_hz = unit.osc_freq;
    // The unit's frequencies are the key's; carry the pitch multiplier over.
    if (mult != 1.0f) {
      unit.osc_freq = base_hz * mult;
      if (!slide) unit.slew_y = unit.osc_freq;
      else unit.slew_y = unit.slew_y * mult;   // ... it was the old key's times mult already
    }
  }

  void NoteOff(uint8_t key) {
    if (key > 127) return;
    bool held = false;
    for (int k = 0; k < n_keys; ++k) held = held || keys[k] == key;
    if (!held) return;
    const bool newest = keys[n_keys - 1] == key;
    Remove(key);
    if (!newest) return;
    if (n_keys > 0) {                          // slide back to the newest still held
      const int back = keys[n_keys - 1];
      NewKey(back);
      base_hz = KeyHz(back);
      unit.osc_freq = mult == 1.0f ? base_hz : base_hz * mult;
    } else {
      bass303_note_off(&unit);
    }
  }

  void PitchBend(float semitones) {
    bend = semitones == semitones ? semitones : 0.0f;
  }

  void SetParam(uint16_t index, float v) {
    if (index >= P_COUNT) return;
    const fm1_param_t &p = kParams[index];
    v = fm1_param_clamp(&p, v);
    if (p.type == FM1_PARAM_ENUM) v = static_cast<float>(static_cast<int>(v + 0.5f));
    if (v == value[index]) return;
    value[index] = v;
    const bool ramp_it = (p.flags & FM1_PARAM_SMOOTH) && !Silent();
    fm1_smooth_set(&ramp[index], &cur[index], v, ramp_it ? steps : 0u);
    if (!ramp_it) {
      Apply();                                 // a LATCH value reaches the next note-on
      if (Silent()) ApplySwitches();
    }
  }

  void SetParamNote(uint8_t key, uint16_t index, float off) {
    if (sounding < 0 || key != sounding) return;
    if (index == FM1_PARAM_NOTE_PITCH) {
      note_pitch = fm1_param_note_offset(NULL, off);
      return;
    }
    if (index >= P_COUNT || !fm1_param_poly(&kParams[index])) return;
    offset[index] = fm1_param_note_offset(&kParams[index], off);
  }
};

size_t InstanceSize(const fm1_host_t *) { return (sizeof(Instance) + 15u) & ~static_cast<size_t>(15u); }

void *Create(void *mem, const fm1_host_t *host) {
  Instance *self = new (mem) Instance();
  if (!self->Init(host)) {
    self->~Instance();
    return NULL;
  }
  return self;
}

void Destroy(void *self) { static_cast<Instance *>(self)->~Instance(); }
void NoteOn(void *s, uint8_t k, uint8_t v) { static_cast<Instance *>(s)->NoteOn(k, v); }
void NoteOff(void *s, uint8_t k) { static_cast<Instance *>(s)->NoteOff(k); }
void Bend(void *s, float st) { static_cast<Instance *>(s)->PitchBend(st); }
void Set(void *s, uint16_t i, float v) { static_cast<Instance *>(s)->SetParam(i, v); }
void Render(void *s, float *out, uint32_t n) { static_cast<Instance *>(s)->Render(out, n); }
void SetNote(void *s, uint8_t k, uint16_t i, float o) {
  static_cast<Instance *>(s)->SetParamNote(k, i, o);
}

}  // namespace acid_bass
}  // namespace fm1

extern "C" const fm1_engine_t fm1_engine_acid_bass = {
  FM1_ENGINE_MAGIC, FM1_ENGINE_API_VERSION, FM1_KIND_SOUND,
  "acid-bass", "Acid Bass",
  "A bass after the TB-303: fm1-x0x's 303 by Charles Vestal (GPL-3.0), ported from "
  "schwung-303: Open303 by Robin Schmidt (MIT), Devilfish ranges after jc303 by midilab "
  "(GPL-3.0), RAT drive after dm-Rat by Dave Mollen (GPL-3.0)",
  fm1::acid_bass::kParams, fm1::acid_bass::P_COUNT, 1,
  fm1::acid_bass::InstanceSize, fm1::acid_bass::Create, fm1::acid_bass::Destroy,
  fm1::acid_bass::NoteOn, fm1::acid_bass::NoteOff, fm1::acid_bass::Bend,
  fm1::acid_bass::Set, fm1::acid_bass::Render,
  fm1::acid_bass::SetNote,
  0, NULL,                  // API v3: no effect extension
  0, 0,                     // not a pad kit
};

// For the oracle (engines/test/acid_oracle.cc): the vendored unit inside an
// instance, to copy and drive beside it.
extern "C" const bass303_t *fm1_acid_bass_unit(const void *self) {
  return &static_cast<const fm1::acid_bass::Instance *>(self)->unit;
}
