/* felucca_bridge.c -- the C side of the Felucca shim (felucca_bridge.h).
 *
 * Includes Felucca's own files, unmodified (third_party/felucca/src, and
 * gen/felucca_tables.h, the output of its tools/gen_tables.py), the way
 * Felucca's felucca.c includes them: the tables, core.h, dsp.c, then the
 * engines. Two definitions are made around core.h, neither of which
 * changes what the engines compute:
 *   - core.h's last line puts a boot-loop record in a ".noinit" section,
 *     which only the FM-1's linker script has (Mach-O cannot even name it).
 *     `section` is defined to `unused` for that line, and the record is
 *     renamed, so it is a plain unused variable here;
 *   - core.h defines the four parts, trk[4]. Our instances each hold one
 *     part of their own, so `trk` is defined, after core.h, as the part the
 *     current call works on. An engine that finds its part as `t - trk`
 *     (WHEEL, for its arrays below) then finds part 0.
 * WHEEL keeps its per-part and per-voice state in static arrays of its own
 * (eng_wheel.c, drw_t and drw_v). The world holds a copy of part 0's, which
 * the bridge copies into those arrays at the start of each call that runs
 * WHEEL code and back at its end: 832 bytes each way, once a control block
 * and once a note-on [verified: tools/jieli/sizes_felucca.c, 96 + 8 x 92
 * bytes on pi32v2, i386 and x86-64]. The arrays themselves are sized for
 * Felucca's four parts, 3,328 bytes of static RAM of which part 0's are used.
 * The audio task is the only caller (fm1_engine.h, "Threads").
 *
 * Above the engines this file does what Felucca's voice.c does for a voice,
 * in our own code: the envelope (attack, decay to the sustain level and
 * release, at the control rate, on Felucca's tables, as its env_tick), the
 * modulation an engine reads (vmod_t: the amplitude ramp, the pitch, the
 * cutoff with the envelope amount and the accent, the shape), and the
 * retrigger of a sounding voice (the attack from where the level is, the
 * phases kept). Voice allocation, glide and parameters are the shim's.
 *
 * Integer arithmetic throughout, as Felucca's: every build gives the same
 * bits. Compiled with -fwrapv (mk/felucca.mk): the engines multiply and
 * shift signed values as Felucca's own builds do.
 *
 * Built only while the GPL switch is on (FM1_GPL_MODS, engines/Makefile;
 * mk/felucca.mk): the object holds GPL-3.0-only code. MIT licence (this
 * file's own text).
 */
#include "fm1_gpl_mods.h"   /* FM1_GPL_MODS, generated by engines/Makefile */

#if !FM1_GPL_MODS
#error "felucca_bridge.c includes GPL code: it is built only with FM1_GPL_MODS=1 (engines/mk/felucca.mk)"
#endif

#include <stddef.h>
#include <stdint.h>
#include <string.h>

#include "felucca_bridge.h"

/* ---- Felucca, as felucca.c includes it ---------------------------------- */
#include "felucca_tables.h"             /* gen/: tools/gen_tables.py's output */

#define section(x) unused               /* core.h's ".noinit" boot-loop record */
#define bootguard fel_bootguard_unused
#include "core.h"
#undef bootguard
#undef section

static track_t *fel_part;               /* the part the current call works on */
#define trk (fel_part)

#include "dsp.c"
#include "eng_wheel.c"
#include "eng_trio.c"
#include "eng_phase.c"

#undef trk

/* ---- The world ------------------------------------------------------------ */
typedef struct fel_world {
  track_t t;                            /* the part: parameters, voices */
  /* WHEEL only (fel_world_size leaves them out for the others): */
  drw_trk_t wheel_part;                 /* eng_wheel.c drw_t[0] */
  drw_vc_t wheel_voice[NVOICE];         /* eng_wheel.c drw_v[0] */
} fel_world_t;

typedef char fel_voices_match[NVOICE == FEL_VOICES && CTL == FEL_CTL && FS == FEL_RATE ? 1 : -1];

static const engine_t *const FEL_ENG[FEL_ENGINES] = { &ENG_WHEEL, &ENG_TRIO, &ENG_PHASE };

static const engine_t *fel_eng(int engine) {
  return FEL_ENG[engine >= 0 && engine < FEL_ENGINES ? engine : 0];
}

size_t fel_world_size(int engine) {
  return engine == FEL_WHEEL ? sizeof(fel_world_t) : offsetof(fel_world_t, wheel_part);
}

size_t fel_sizeof_track(void) { return sizeof(track_t); }

void fel_world_init(void *mem, int engine) {
  fel_world_t *w = (fel_world_t *)mem;
  memset(w, 0, fel_world_size(engine));
  w->t.engine = w->t.eng_req = (uint8_t)(engine == FEL_WHEEL ? 7 : engine == FEL_TRIO ? 6 : 2);
}

/* WHEEL's arrays: part 0's state from the world, and back. */
static void fel_lend(fel_world_t *w, int engine) {
  fel_part = &w->t;
  if (engine != FEL_WHEEL) return;
  memcpy(&drw_t[0], &w->wheel_part, sizeof(drw_trk_t));
  memcpy(drw_v[0], w->wheel_voice, sizeof(w->wheel_voice));
}

static void fel_take(fel_world_t *w, int engine) {
  if (engine == FEL_WHEEL) {
    memcpy(&w->wheel_part, &drw_t[0], sizeof(drw_trk_t));
    memcpy(w->wheel_voice, drw_v[0], sizeof(w->wheel_voice));
  }
  fel_part = 0;
}

static void fel_set_e(track_t *t, const int16_t e[FEL_EDIT]) {
  int k;
  for (k = 0; k < FEL_EDIT; ++k) t->p[P_E0 + k] = e[k];
}

/* ---- Voices ----------------------------------------------------------------- */
void fel_voice_start(void *mem, int engine, int voice, uint8_t note, uint8_t velocity,
                     uint32_t age, int32_t pitch_cur, const int16_t e[FEL_EDIT]) {
  fel_world_t *w = (fel_world_t *)mem;
  const engine_t *eng = fel_eng(engine);
  track_t *t = &w->t;
  voice_t *v = &t->v[voice & (NVOICE - 1)];
  const int sounding = v->active && v->stage != 0;
  uint32_t ph[3];
  int32_t s[8];
  int k;
  memcpy(ph, v->ph, sizeof ph);
  memcpy(s, v->s, sizeof s);
  v->note = note;
  v->vel = velocity;
  v->gate = 1;
  v->active = 1;
  v->stage = 1;
  v->age = age;
  v->pitch16 = (int32_t)note * 16;
  v->pitch_cur = pitch_cur;
  if (!sounding) {                      /* else the attack starts from where the level is */
    v->env = 0;
    v->env_out = 0;
  }
  fel_set_e(t, e);
  fel_lend(w, engine);
  eng->note_on(t, v);
  fel_take(w, engine);
  if (sounding && !eng->sampled) {      /* a retrigger keeps the phases (no click), and the */
    memcpy(v->ph, ph, sizeof ph);       /* engine's filter states it marks (engine_t.keep) */
    for (k = 0; k < 8; ++k) {
      if (k != 2 && k != 3 && (eng->keep >> k) & 1u) v->s[k] = s[k];
    }
  }
}

void fel_voice_release(void *mem, int voice) {
  voice_t *v = &((fel_world_t *)mem)->t.v[voice & (NVOICE - 1)];
  if (v->active && v->gate) {
    v->gate = 0;
    v->stage = 3;
  }
}

void fel_voice_retune(void *mem, int voice, uint8_t note) {
  voice_t *v = &((fel_world_t *)mem)->t.v[voice & (NVOICE - 1)];
  v->note = note;
  v->pitch16 = (int32_t)note * 16;
}

int fel_voice_active(const void *mem, int voice) {
  return ((const fel_world_t *)mem)->t.v[voice & (NVOICE - 1)].active != 0;
}

/* The envelope, one control tick, Felucca's law (voice.c env_tick): a linear
 * attack to full level in the attack time, then an exponential approach to
 * the sustain level and, after the key, to 0, each 99 % of the way in its
 * time; a release that falls below 1/4096 ends the voice. Q24 inside,
 * Q15 out. */
static int32_t fel_env_tick(voice_t *v, const uint8_t adsr[4]) {
  switch (v->stage) {
    case 1:
      v->env += (int32_t)ENV_LIN[adsr[0] & 127];
      if (v->env >= (1 << 24)) {
        v->env = 1 << 24;
        v->stage = 2;
      }
      break;
    case 2: {
      const int32_t sus = (int32_t)(adsr[2] & 127) << 17;
      v->env += mulq16(sus - v->env, ENV_EXP[adsr[1] & 127]);
      break;
    }
    case 3:
      v->env -= mulq16(v->env, ENV_EXP[adsr[3] & 127]);
      if (v->env < (1 << 12)) {
        v->env = 0;
        v->stage = 0;
        v->active = 0;                  /* this block still renders, its ramp down to 0 */
      }
      break;
    default:
      v->env = 0;
      break;
  }
  return v->env >> 9;
}

void fel_block(void *mem, int engine, const int16_t part_e[FEL_EDIT], const fel_vin_t in[FEL_VOICES]) {
  fel_world_t *w = (fel_world_t *)mem;
  const engine_t *eng = fel_eng(engine);
  track_t *t = &w->t;
  int i;
  fel_set_e(t, part_e);
  fel_lend(w, engine);
  if (eng->block) eng->block(t);
  for (i = 0; i < NVOICE; ++i) {
    voice_t *v = &t->v[i];
    const fel_vin_t *x = &in[i];
    vmod_t m;
    int32_t env;
    if (!v->active) continue;
    env = fel_env_tick(v, x->adsr);
    if (eng->amp) env = eng->amp(t, v, env);
    m.envq15 = env;
    m.amp1 = mulq15(env, v->vel * 258);
    m.amp0 = v->env_out;
    v->env_out = m.amp1;
    if (!env && !m.amp0 && v->stage == 2 && !eng->sampled)
      continue;                         /* held at a silent sustain: nothing to render */
    v->pitch_cur = x->pitch_cur;
    m.pitch16 = clamp(x->pitch16, 0, 2047);
    m.inc = pitch_inc((uint32_t)m.pitch16);
    m.fine = x->fine;
    if (m.fine) m.inc += (uint32_t)((int32_t)(m.inc >> 12) * m.fine);
    m.cutoff = x->cutoff + ((env * x->fenv) >> 7);
    if (v->vel > 110) m.cutoff += (env * 24) >> 7;   /* an accent opens the filter with the envelope */
    m.shape = x->shape;
    fel_set_e(t, x->e);
    eng->render(t, v, x->out, CTL, &m);
  }
  fel_set_e(t, part_e);
  fel_take(w, engine);
}

/* ---- Tables and presets ---------------------------------------------------- */
uint32_t fel_time_ms_x10(int i) { return TIME_MS_X10[i & 127]; }
uint32_t fel_cutoff_hz(int i) { return CUTOFF_HZ[i & 127]; }

int fel_preset(int engine, int index, fel_preset_t *out) {
  const engine_t *eng = fel_eng(engine);
  const preset_t *p;
  int k;
  if (index < 0 || index >= eng->npresets) return 0;
  p = &eng->presets[index];
  out->name = p->name;
  for (k = 0; k < FEL_EDIT; ++k) out->e[k] = p->e[k];
  for (k = 0; k < 4; ++k) out->env[k] = p->env[k];
  out->fenv = p->fenv;
  out->mono = p->mono;
  return 1;
}
