// registry.cc -- the static engine registry (docs/11 §5.2, tier 0), and the
// licence table (fm1_engine.h, "Licences").
// Engines are compiled in; adding one is a line here and a line in the Makefile.
// A GPL module's lines go under #if FM1_GPL_MODS (the GPL switch,
// engines/Makefile; CLAUDE.md, "The GPL switch"), here and in its fragment,
// so a build with the switch off neither lists nor links it.
// MIT licence.

#include "fm1_engine.h"
#include "fm1_gpl_mods.h"   // FM1_GPL_MODS, generated by engines/Makefile

#include <cstring>

#if !defined(FM1_GPL_MODS) || (FM1_GPL_MODS != 0 && FM1_GPL_MODS != 1)
#error "FM1_GPL_MODS must be 0 or 1 (engines/Makefile)"
#endif

extern "C" {
extern const fm1_engine_t fm1_engine_macro;
extern const fm1_engine_t fm1_engine_shapes;
extern const fm1_engine_t fm1_engine_macro_heavy;
extern const fm1_engine_t fm1_engine_sixop;
extern const fm1_engine_t fm1_engine_dx7;
extern const fm1_engine_t fm1_engine_sw_sophie;
extern const fm1_engine_t fm1_engine_drums;
extern const fm1_engine_t fm1_engine_test_sine;
extern const fm1_engine_t fm1_engine_plate;
extern const fm1_engine_t fm1_engine_ensemble;
extern const fm1_engine_t fm1_engine_diffuse;
extern const fm1_engine_t fm1_engine_sw_psxverb;
extern const fm1_engine_t fm1_engine_crush;
extern const fm1_engine_t fm1_engine_fold;
extern const fm1_engine_t fm1_engine_drive;
extern const fm1_engine_t fm1_engine_echo;
extern const fm1_engine_t fm1_engine_filter;
extern const fm1_engine_t fm1_engine_comb;
extern const fm1_engine_t fm1_engine_comp;
extern const fm1_engine_t fm1_engine_limit;
extern const fm1_engine_t fm1_engine_djfilter;
extern const fm1_engine_t fm1_engine_tilt;
extern const fm1_engine_t fm1_engine_sat;
extern const fm1_engine_t fm1_engine_isolator;
extern const fm1_engine_t fm1_engine_eq;
extern const fm1_engine_t fm1_engine_room;
extern const fm1_engine_t fm1_engine_hall;
extern const fm1_engine_t fm1_engine_gate;
extern const fm1_engine_t fm1_engine_squash;
extern const fm1_engine_t fm1_engine_shaper;
extern const fm1_engine_t fm1_engine_test_gain;
extern const fm1_engine_t fm1_engine_test_ext;
#if FM1_GPL_MODS
// GPL modules (each in its own third_party/<name>/, built by its own fragment).
extern const fm1_engine_t fm1_engine_acid_bass;   // fm1-x0x's 303 (mk/fm1-x0x.mk)
extern const fm1_engine_t fm1_engine_comet_kit;   // fm1-x0x's 909 (mk/fm1-x0x.mk)
extern const fm1_engine_t fm1_engine_crater;      // fm1-x0x's 808 (mk/x0x-crater.mk)
#endif

const fm1_engine_t *const fm1_engines[] = {
  // sound engines
  &fm1_engine_macro,
  &fm1_engine_shapes,
  &fm1_engine_macro_heavy,
  &fm1_engine_sixop,
  &fm1_engine_dx7,
  &fm1_engine_sw_sophie,
  &fm1_engine_drums,
#if FM1_GPL_MODS
  // GPL sound engines.
  &fm1_engine_acid_bass,
  &fm1_engine_comet_kit,
  &fm1_engine_crater,
#endif
  &fm1_engine_test_sine,
  // audio effects
  &fm1_engine_plate,
  &fm1_engine_ensemble,
  &fm1_engine_diffuse,
  &fm1_engine_sw_psxverb,
  &fm1_engine_crush,
  &fm1_engine_fold,
  &fm1_engine_drive,
  &fm1_engine_echo,
  &fm1_engine_filter,
  &fm1_engine_comb,
  &fm1_engine_comp,
  &fm1_engine_limit,
  &fm1_engine_djfilter,
  &fm1_engine_tilt,
  &fm1_engine_sat,
  &fm1_engine_isolator,
  &fm1_engine_eq,
  &fm1_engine_room,
  &fm1_engine_hall,
  &fm1_engine_gate,
  &fm1_engine_squash,
  &fm1_engine_shaper,
  &fm1_engine_test_gain,
  &fm1_engine_test_ext,
};
const size_t fm1_engine_count = sizeof(fm1_engines) / sizeof(fm1_engines[0]);

const fm1_engine_t *fm1_engine_find(const char *id) {
  for (size_t i = 0; i < fm1_engine_count; ++i) {
    if (strcmp(fm1_engines[i]->id, id) == 0) return fm1_engines[i];
  }
  return NULL;
}

// The licence table: every module, engine, effect or MIDI effect, whose code
// is not all MIT, with the SPDX expression of what it links and where its
// vendored code is. Every other module is MIT (fm1_engine_licence). A GPL
// module's row goes under #if FM1_GPL_MODS, as its registry entry does;
// tests/test_gpl_switch.py checks that the two agree in both builds.
const fm1_licence_t fm1_licences[] = {
  // FM6: msfa, Google's FM core (Apache-2.0), under our MIT voice and tables.
  { "dx7", "MIT AND Apache-2.0", "engines/third_party/msfa" },
#if FM1_GPL_MODS
  // fm1-x0x (Charles Vestal, GPL-3.0-only): Acid Bass on its 303, which
  // carries Open303 (MIT); our wrapper is MIT.
  { "acid-bass", "GPL-3.0-only AND MIT", "engines/third_party/fm1-x0x" },
  // ...and Acid Gen (a MIDI effect) on its TB-3PO; our wrapper is MIT.
  { "acid-gen", "GPL-3.0-only AND MIT", "engines/third_party/fm1-x0x" },
  // ...and Comet Kit on its 909, with ER-99's cymbal recordings (GPL-3.0);
  // our wrapper is MIT.
  { "comet", "GPL-3.0-only AND MIT", "engines/third_party/fm1-x0x" },
  // ...and Crater Kit on its 808, whose rim shot is after sc808 (MIT); our
  // wrapper is MIT.
  { "crater", "GPL-3.0-only AND MIT", "engines/third_party/fm1-x0x" },
#endif
};
const size_t fm1_licence_count = sizeof(fm1_licences) / sizeof(fm1_licences[0]);
const int fm1_gpl_mods = FM1_GPL_MODS;

const fm1_licence_t *fm1_engine_licence_row(const fm1_engine_t *e) {
  for (size_t i = 0; e && e->id && i < fm1_licence_count; ++i) {
    if (strcmp(fm1_licences[i].id, e->id) == 0) return &fm1_licences[i];
  }
  return NULL;
}

const char *fm1_engine_licence(const fm1_engine_t *e) {
  const fm1_licence_t *row = fm1_engine_licence_row(e);
  return row ? row->spdx : "MIT";
}
}
