// registry.cc -- the static engine registry (docs/11 §5.2, tier 0), and the
// licence table (fm1_engine.h, "Licences").
// Engines are compiled in; adding one is a line here and a line in the Makefile.
// A GPL module's lines go under #if FM1_GPL_MODS (the GPL switch,
// engines/Makefile; CLAUDE.md, "The GPL switch"), here and in its fragment,
// so a build with the switch off neither lists nor links it. Every entry and
// licence row is also FM1_IF(FM1_WITH_<ID>, ...): the module list
// (FM1_MODULES, engines/modules/catalogue.mk) keeps only the modules chosen.
// MIT licence.

#include "fm1_engine.h"
#include "fm1_gpl_mods.h"   // FM1_GPL_MODS, generated by engines/Makefile
#include "fm1_known.h"
#include "fm1_modules.h"    // FM1_WITH_*, FM1_IF: the module list, generated

#include <cstring>

#if !defined(FM1_GPL_MODS) || (FM1_GPL_MODS != 0 && FM1_GPL_MODS != 1)
#error "FM1_GPL_MODS must be 0 or 1 (engines/Makefile)"
#endif

extern "C" {
extern const fm1_engine_t fm1_engine_macro;
extern const fm1_engine_t fm1_engine_shapes;
extern const fm1_engine_t fm1_engine_macro_heavy;
extern const fm1_engine_t fm1_engine_sixop;
extern const fm1_engine_t fm1_engine_dx7;
extern const fm1_engine_t fm1_engine_sw_sophie;
extern const fm1_engine_t fm1_engine_drums;
extern const fm1_engine_t fm1_engine_test_sine;
extern const fm1_engine_t fm1_engine_plate;
extern const fm1_engine_t fm1_engine_ensemble;
extern const fm1_engine_t fm1_engine_diffuse;
extern const fm1_engine_t fm1_engine_sw_psxverb;
extern const fm1_engine_t fm1_engine_crush;
extern const fm1_engine_t fm1_engine_fold;
extern const fm1_engine_t fm1_engine_drive;
extern const fm1_engine_t fm1_engine_echo;
extern const fm1_engine_t fm1_engine_warble;
extern const fm1_engine_t fm1_engine_filter;
extern const fm1_engine_t fm1_engine_comb;
extern const fm1_engine_t fm1_engine_comp;
extern const fm1_engine_t fm1_engine_limit;
extern const fm1_engine_t fm1_engine_djfilter;
extern const fm1_engine_t fm1_engine_tilt;
extern const fm1_engine_t fm1_engine_sat;
extern const fm1_engine_t fm1_engine_isolator;
extern const fm1_engine_t fm1_engine_eq;
extern const fm1_engine_t fm1_engine_room;
extern const fm1_engine_t fm1_engine_hall;
extern const fm1_engine_t fm1_engine_gate;
extern const fm1_engine_t fm1_engine_squash;
extern const fm1_engine_t fm1_engine_shaper;
extern const fm1_engine_t fm1_engine_test_gain;
extern const fm1_engine_t fm1_engine_test_ext;
#if FM1_GPL_MODS
// GPL modules (each in its own third_party/<name>/, built by its own fragment).
extern const fm1_engine_t fm1_engine_acid_bass;   // fm1-x0x's 303 (mk/fm1-x0x.mk)
extern const fm1_engine_t fm1_engine_comet_kit;   // fm1-x0x's 909 (mk/fm1-x0x.mk)
extern const fm1_engine_t fm1_engine_crater;      // fm1-x0x's 808 (mk/x0x-crater.mk)
extern const fm1_engine_t fm1_engine_drawbar;     // Felucca's WHEEL (mk/felucca.mk)
extern const fm1_engine_t fm1_engine_trio;        // Felucca's TRIO
extern const fm1_engine_t fm1_engine_phase_bend;  // Felucca's PHASE
#endif

const fm1_engine_t *const fm1_engines[] = {
  // sound engines
  FM1_IF(FM1_WITH_MACRO, &fm1_engine_macro)
  FM1_IF(FM1_WITH_SHAPES, &fm1_engine_shapes)
  FM1_IF(FM1_WITH_MACRO_HEAVY, &fm1_engine_macro_heavy)
  FM1_IF(FM1_WITH_SIXOP, &fm1_engine_sixop)
  FM1_IF(FM1_WITH_DX7, &fm1_engine_dx7)
  FM1_IF(FM1_WITH_SW_SOPHIE, &fm1_engine_sw_sophie)
  FM1_IF(FM1_WITH_DRUMS, &fm1_engine_drums)
#if FM1_GPL_MODS
  // GPL sound engines.
  FM1_IF(FM1_WITH_ACID_BASS, &fm1_engine_acid_bass)
  FM1_IF(FM1_WITH_COMET, &fm1_engine_comet_kit)
  FM1_IF(FM1_WITH_CRATER, &fm1_engine_crater)
  FM1_IF(FM1_WITH_DRAWBAR, &fm1_engine_drawbar)
  FM1_IF(FM1_WITH_TRIO, &fm1_engine_trio)
  FM1_IF(FM1_WITH_PHASE_BEND, &fm1_engine_phase_bend)
#endif
  FM1_IF(FM1_WITH_TEST_SINE, &fm1_engine_test_sine)
  // audio effects
  FM1_IF(FM1_WITH_PLATE, &fm1_engine_plate)
  FM1_IF(FM1_WITH_ENSEMBLE, &fm1_engine_ensemble)
  FM1_IF(FM1_WITH_DIFFUSE, &fm1_engine_diffuse)
  FM1_IF(FM1_WITH_SW_PSXVERB, &fm1_engine_sw_psxverb)
  FM1_IF(FM1_WITH_CRUSH, &fm1_engine_crush)
  FM1_IF(FM1_WITH_FOLD, &fm1_engine_fold)
  FM1_IF(FM1_WITH_DRIVE, &fm1_engine_drive)
  FM1_IF(FM1_WITH_ECHO, &fm1_engine_echo)
  FM1_IF(FM1_WITH_WARBLE, &fm1_engine_warble)
  FM1_IF(FM1_WITH_FILTER, &fm1_engine_filter)
  FM1_IF(FM1_WITH_COMB, &fm1_engine_comb)
  FM1_IF(FM1_WITH_COMP, &fm1_engine_comp)
  FM1_IF(FM1_WITH_LIMIT, &fm1_engine_limit)
  FM1_IF(FM1_WITH_DJFILTER, &fm1_engine_djfilter)
  FM1_IF(FM1_WITH_TILT, &fm1_engine_tilt)
  FM1_IF(FM1_WITH_SAT, &fm1_engine_sat)
  FM1_IF(FM1_WITH_ISOLATOR, &fm1_engine_isolator)
  FM1_IF(FM1_WITH_EQ, &fm1_engine_eq)
  FM1_IF(FM1_WITH_ROOM, &fm1_engine_room)
  FM1_IF(FM1_WITH_HALL, &fm1_engine_hall)
  FM1_IF(FM1_WITH_GATE, &fm1_engine_gate)
  FM1_IF(FM1_WITH_SQUASH, &fm1_engine_squash)
  FM1_IF(FM1_WITH_SHAPER, &fm1_engine_shaper)
  FM1_IF(FM1_WITH_TEST_GAIN, &fm1_engine_test_gain)
  FM1_IF(FM1_WITH_TEST_EXT, &fm1_engine_test_ext)
};
const size_t fm1_engine_count = sizeof(fm1_engines) / sizeof(fm1_engines[0]);

const fm1_engine_t *fm1_engine_find(const char *id) {
  for (size_t i = 0; i < fm1_engine_count; ++i) {
    if (strcmp(fm1_engines[i]->id, id) == 0) return fm1_engines[i];
  }
  return NULL;
}

// The licence table: every module, engine, effect or MIDI effect, whose code
// is not all MIT, with the SPDX expression of what it links and where its
// vendored code is. Every other module is MIT (fm1_engine_licence). A GPL
// module's row goes under #if FM1_GPL_MODS, as its registry entry does;
// tests/test_gpl_switch.py checks that the two agree in both builds.
const fm1_licence_t fm1_licences[] = {
  // FM6: msfa, Google's FM core (Apache-2.0), under our MIT voice and tables.
  FM1_IF(FM1_WITH_DX7, { "dx7", "MIT AND Apache-2.0", "engines/third_party/msfa" })
#if FM1_GPL_MODS
  // fm1-x0x (Charles Vestal, GPL-3.0-only): Acid Bass on its 303, which
  // carries Open303 (MIT); our wrapper is MIT.
  FM1_IF(FM1_WITH_ACID_BASS, { "acid-bass", "GPL-3.0-only AND MIT", "engines/third_party/fm1-x0x" })
  // ...and Acid Gen (a MIDI effect) on its TB-3PO; our wrapper is MIT.
  FM1_IF(FM1_WITH_ACID_GEN, { "acid-gen", "GPL-3.0-only AND MIT", "engines/third_party/fm1-x0x" })
  // ...and Comet Kit on its 909, with ER-99's cymbal recordings (GPL-3.0);
  // our wrapper is MIT.
  FM1_IF(FM1_WITH_COMET, { "comet", "GPL-3.0-only AND MIT", "engines/third_party/fm1-x0x" })
  // ...and Crater Kit on its 808, whose rim shot is after sc808 (MIT); our
  // wrapper is MIT.
  FM1_IF(FM1_WITH_CRATER, { "crater", "GPL-3.0-only AND MIT", "engines/third_party/fm1-x0x" })
  // Felucca (Leo Kuroshita, Hügelton Instruments; GPL-3.0-only): three of its
  // engines, unmodified, under our MIT shim and bridge.
  FM1_IF(FM1_WITH_DRAWBAR, { "drawbar", "GPL-3.0-only AND MIT", "engines/third_party/felucca" })
  FM1_IF(FM1_WITH_TRIO, { "trio", "GPL-3.0-only AND MIT", "engines/third_party/felucca" })
  FM1_IF(FM1_WITH_PHASE_BEND, { "phase-bend", "GPL-3.0-only AND MIT", "engines/third_party/felucca" })
#endif
  { NULL, NULL, NULL }    // the end: a list may leave every row out
};
const size_t fm1_licence_count = sizeof(fm1_licences) / sizeof(fm1_licences[0]) - 1;
const int fm1_gpl_mods = FM1_GPL_MODS;

const fm1_licence_t *fm1_engine_licence_row(const fm1_engine_t *e) {
  for (size_t i = 0; e && e->id && i < fm1_licence_count; ++i) {
    if (strcmp(fm1_licences[i].id, e->id) == 0) return &fm1_licences[i];
  }
  return NULL;
}

const char *fm1_engine_licence(const fm1_engine_t *e) {
  const fm1_licence_t *row = fm1_engine_licence_row(e);
  return row ? row->spdx : "MIT";
}

// The modules this build could have but its list leaves out (fm1_modules.h),
// as known ids with the reason "list" (fm1_known.h): the metadata export
// names them and a load that meets one says why.
const char *const fm1_modules_name = FM1_MODULES_NAME;
const fm1_known_id_t fm1_left_out[] = {
  FM1_LEFT_OUT_ROWS
  { NULL, NULL, NULL, NULL }
};
const size_t fm1_left_out_count = sizeof(fm1_left_out) / sizeof(fm1_left_out[0]) - 1;

const fm1_known_id_t *fm1_absent_find(const char *id) {
  for (const fm1_known_id_t *k = fm1_left_out; id && k->id; ++k) {
    if (strcmp(k->id, id) == 0) return k;
  }
  return fm1_known_id_find(id);
}
}
