#!/usr/bin/env python3
"""Write engines/mod/mod_mi_tables.c: the tables the C ports in mod_mi.c
share with their Mutable Instruments originals (docs/16 MG2).

  lut_delay_times  Peaks' pulse delays (peaks/resources.cc), 257 entries
  lut_gravity      Peaks' bouncing-ball gravities (peaks/resources.cc)
  scales           Braids' 49 quantizer scales (braids/quantizer_scales.h)

They are read from the vendored copies under engines/third_party/mutable
(eurorack 08460a6, byte-identical to upstream, UPSTREAM.md), so the ports
use upstream's own numbers; fm1-mod-mi-ref compares them again, element by
element, with the compiled originals. Emilie Gillet's MIT notice travels
with the data into the C file.

  python3 engines/mod/gen_mi_tables.py           # rewrite mod_mi_tables.c
  python3 engines/mod/gen_mi_tables.py --check   # exit 1 if it is out of date
"""
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
MUTABLE = HERE.parent / "third_party" / "mutable"
OUT = HERE / "mod_mi_tables.c"

NOTICE = """\
 * Copyright 2013 Emilie Gillet (Peaks' tables); copyright 2015 Emilie Gillet
 * (Braids' scales).
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE."""


def lut(text, name):
    m = re.search(r"const uint16_t %s\[\] = \{([^}]*)\};" % name, text)
    if not m:
        raise SystemExit(f"{name} not found")
    values = [int(v) for v in re.findall(r"-?\d+", m.group(1))]
    if len(values) != 257:
        raise SystemExit(f"{name}: {len(values)} entries, want 257")
    return values


def scales(text):
    body = text[text.index("const Scale scales[] = {"):]
    body = body[:body.index("\n};")]
    out = []
    for comment, span, n, notes in re.findall(
            r"//\s*([^\n]*)\n\s*\{\s*([^,]+),\s*(\d+),\s*\{([^}]*)\}\s*\}", body):
        span = span.strip()
        m = re.fullmatch(r"(\d+)\s*<<\s*(\d+)", span)
        span = int(m.group(1)) << int(m.group(2)) if m else int(span)
        notes = [int(v) for v in re.findall(r"-?\d+", notes)]
        if len(notes) != int(n):
            raise SystemExit(f"scale {comment}: {len(notes)} notes, want {n}")
        out.append((comment.strip(), span, notes))
    if len(out) != 49:
        raise SystemExit(f"{len(out)} scales, want 49")
    return out


def rows(values, per=12):
    return "\n".join("  " + ", ".join(str(v) for v in values[i:i + per]) + ","
                     for i in range(0, len(values), per))


def render():
    peaks = (MUTABLE / "peaks" / "resources.cc").read_text()
    braids = (MUTABLE / "braids" / "quantizer_scales.h").read_text()
    lines = [
        "/* mod_mi_tables.c -- generated by engines/mod/gen_mi_tables.py from the",
        " * vendored engines/third_party/mutable/peaks/resources.cc and",
        " * braids/quantizer_scales.h (eurorack 08460a6); do not edit.",
        " *",
        NOTICE,
        " */",
        '#include "mod_mi.h"',
        "",
        "const uint16_t mod_mi_lut_delay_times[MOD_MI_LUT_SIZE] = {",
        rows(lut(peaks, "lut_delay_times")),
        "};",
        "",
        "const uint16_t mod_mi_lut_gravity[MOD_MI_LUT_SIZE] = {",
        rows(lut(peaks, "lut_gravity")),
        "};",
        "",
        "const mod_mi_scale_t mod_mi_scales[MOD_MI_SCALES] = {",
    ]
    for comment, span, notes in scales(braids):
        padded = notes + [0] * (16 - len(notes))
        lines.append(f"  {{ {span}, {len(notes)}, 0, {{ {', '.join(str(v) for v in padded)} }} }},"
                     f"  /* {comment} */")
    lines += ["};", ""]
    return "\n".join(lines)


def main():
    text = render()
    if "--check" in sys.argv[1:]:
        if not OUT.exists() or OUT.read_text() != text:
            print(f"{OUT} is out of date; run {Path(__file__).name}", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
