#!/usr/bin/env python3
"""Write engines/mod/mp_tables.c, the modulation primitives' lookup tables.

The formulas are Peaks' (Emilie Gillet, MIT), from
pichenettes/eurorack peaks/resources/lookup_tables.py at 08460a6:

- envelope curves, lines 122-129: expo = 1 - exp(-4t), quartic = t^3.32,
  each normalised to end at 1. Peaks builds them on a 257-point ramp whose
  last point repeats the 256th; these use the plain ramp t = i/256, so every
  curve runs exactly from 0 to 1.
- envelope times, lines 55-68: 0.5 ms to 8 s, linear in increment^-0.175.
  Peaks stores 48 kHz phase increments; this stores the times in seconds,
  which is the same curve without a sample rate.

The values are rounded to float32 here, so the C file holds exact literals
and no libm runs on the target.

  python3 engines/mod/gen_tables.py           # rewrite mp_tables.c
  python3 engines/mod/gen_tables.py --check   # exit 1 if it is out of date
"""
import math
import struct
import sys
from pathlib import Path

N = 257
OUT = Path(__file__).resolve().parent / "mp_tables.c"


def f32(x):
    return struct.unpack("<f", struct.pack("<f", x))[0]


def lit(x):
    s = "%.9g" % f32(x)
    if "e" not in s and "." not in s:
        s += ".0"
    return s + "f"


def tables():
    t = [i / 256.0 for i in range(N)]
    expo = [(1.0 - math.exp(-4.0 * x)) / (1.0 - math.exp(-4.0)) for x in t]
    quartic = [x ** 3.32 for x in t]
    logarithmic = [math.log1p(9.0 * x) / math.log(10.0) for x in t]
    g, tmin, tmax = 0.175, 0.0005, 8.0
    times = [(tmin ** g + x * (tmax ** g - tmin ** g)) ** (1.0 / g) for x in t]
    times[0], times[-1] = tmin, tmax
    return [("fm1_mp_curve_expo", expo), ("fm1_mp_curve_quartic", quartic),
            ("fm1_mp_curve_log", logarithmic), ("fm1_mp_env_times", times)]


def render():
    out = ["/* mp_tables.c -- generated by engines/mod/gen_tables.py; do not edit.",
           " * Curves and times from Peaks' lookup_tables.py (Emilie Gillet, MIT),",
           " * see that script for the formulas and the one difference. */",
           '#include "mp_int.h"', ""]
    for name, vals in tables():
        out.append("const float %s[FM1_MP_TABLE_SIZE] = {" % name)
        for i in range(0, N, 6):
            out.append("  " + ", ".join(lit(v) for v in vals[i:i + 6]) + ",")
        out.append("};")
        out.append("")
    return "\n".join(out)


def main():
    text = render()
    if "--check" in sys.argv[1:]:
        if not OUT.exists() or OUT.read_text() != text:
            print("mp_tables.c is out of date: run engines/mod/gen_tables.py", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
