#!/usr/bin/env python3
"""Write engines/mod/mod_curves.c, the modulation matrix's slot curves
(docs/16 §2.4: "33-entry sign-preserving tables, linearly interpolated,
built offline").

Each table holds f(x) for x = i/32, i = 0..32; the runtime applies
sign(s) * f(|s|) for a source value s in -1..1, so every curve passes
through -1, 0 and 1 and keeps the source's sign. The order is
fm1_mod.h's FM1_MOD_CURVE_*:

  LIN     x
  SQUARE  x^2           slow start: fine control near the base
  CUBE    x^3
  ROOT    sqrt(x)       fast start
  CBRT    x^(1/3)
  EXP     (e^(4x) - 1) / (e^4 - 1)
  LOG     ln(1 + (e^4 - 1) x) / 4    (EXP's inverse)
  S       3x^2 - 2x^3   (smoothstep)

The values are rounded to float32 here, so the C file holds exact literals
and no libm runs on the target.

  python3 engines/mod/gen_curves.py           # rewrite mod_curves.c
  python3 engines/mod/gen_curves.py --check   # exit 1 if it is out of date
"""
import math
import struct
import sys
from pathlib import Path

N = 33
OUT = Path(__file__).resolve().parent / "mod_curves.c"
E4 = math.exp(4.0) - 1.0

CURVES = [
    ("LIN", lambda x: x),
    ("SQUARE", lambda x: x * x),
    ("CUBE", lambda x: x ** 3),
    ("ROOT", math.sqrt),
    ("CBRT", lambda x: x ** (1.0 / 3.0)),
    ("EXP", lambda x: (math.exp(4.0 * x) - 1.0) / E4),
    ("LOG", lambda x: math.log1p(E4 * x) / 4.0),
    ("S", lambda x: x * x * (3.0 - 2.0 * x)),
]


def f32(x):
    return struct.unpack("<f", struct.pack("<f", x))[0]


def lit(x):
    s = "%.9g" % f32(x)
    if "e" not in s and "." not in s:
        s += ".0"
    return s + "f"


def tables():
    out = []
    for name, f in CURVES:
        vals = [f(i / 32.0) for i in range(N)]
        vals[0], vals[-1] = 0.0, 1.0
        out.append((name, vals))
    return out


def render():
    out = ["/* mod_curves.c -- generated by engines/mod/gen_curves.py; do not edit.",
           " * The slot curves of the modulation matrix (fm1_mod.h); formulas in",
           " * that script. MIT licence. */",
           '#include "mod_int.h"', "",
           "static const float kCurves[FM1_MOD_CURVE_COUNT][%d] = {" % N]
    for name, vals in tables():
        out.append("  { /* %s */" % name)
        for i in range(0, N, 6):
            out.append("    " + ", ".join(lit(v) for v in vals[i:i + 6]) + ",")
        out.append("  },")
    out += ["};", "",
            "float fm1_mod_curve(unsigned c, float s) {",
            "  float a, pos, f, y;",
            "  int i;",
            "  if (!mod_finite(s)) return 0.0f;",
            "  if (c == FM1_MOD_CURVE_LIN || c >= FM1_MOD_CURVE_COUNT) return s;",
            "  a = s < 0.0f ? -s : s;",
            "  if (a >= 1.0f) return s < 0.0f ? -1.0f : 1.0f;",
            "  pos = a * 32.0f;",
            "  i = (int)pos;",
            "  f = pos - (float)i;",
            "  y = kCurves[c][i] + (kCurves[c][i + 1] - kCurves[c][i]) * f;",
            "  return s < 0.0f ? -y : y;",
            "}", ""]
    return "\n".join(out)


def main():
    text = render()
    if "--check" in sys.argv[1:]:
        if not OUT.exists() or OUT.read_text() != text:
            print("mod_curves.c is out of date: run engines/mod/gen_curves.py", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
