/* mod_mi_tables.c -- generated by engines/mod/gen_mi_tables.py from the
 * vendored engines/third_party/mutable/peaks/resources.cc and
 * braids/quantizer_scales.h (eurorack 08460a6); do not edit.
 *
 * Copyright 2013 Emilie Gillet (Peaks' tables); copyright 2015 Emilie Gillet
 * (Braids' scales).
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
#include "mod_mi.h"

const uint16_t mod_mi_lut_delay_times[MOD_MI_LUT_SIZE] = {
  5, 7, 8, 10, 12, 14, 16, 18, 21, 24, 27, 31,
  34, 39, 43, 48, 53, 59, 65, 71, 78, 85, 93, 101,
  109, 118, 128, 138, 149, 160, 172, 185, 198, 212, 226, 241,
  257, 273, 290, 308, 327, 347, 367, 388, 410, 433, 456, 481,
  506, 533, 560, 588, 617, 648, 679, 711, 745, 779, 815, 851,
  889, 928, 968, 1009, 1052, 1096, 1141, 1187, 1235, 1284, 1334, 1386,
  1439, 1493, 1549, 1607, 1666, 1726, 1788, 1851, 1916, 1982, 2050, 2120,
  2192, 2265, 2339, 2416, 2494, 2574, 2655, 2739, 2824, 2911, 3000, 3091,
  3184, 3278, 3375, 3474, 3574, 3677, 3782, 3888, 3997, 4108, 4221, 4337,
  4454, 4574, 4696, 4820, 4946, 5075, 5206, 5340, 5475, 5614, 5754, 5897,
  6043, 6191, 6341, 6494, 6650, 6808, 6969, 7133, 7299, 7468, 7639, 7814,
  7991, 8171, 8353, 8539, 8727, 8919, 9113, 9310, 9510, 9713, 9920, 10129,
  10341, 10556, 10775, 10996, 11221, 11449, 11680, 11915, 12152, 12393, 12638, 12885,
  13137, 13391, 13649, 13910, 14175, 14444, 14715, 14991, 15270, 15553, 15839, 16129,
  16423, 16720, 17021, 17326, 17635, 17947, 18264, 18584, 18908, 19236, 19568, 19905,
  20245, 20589, 20937, 21289, 21646, 22007, 22371, 22740, 23114, 23491, 23873, 24259,
  24650, 25045, 25444, 25848, 26256, 26668, 27086, 27507, 27934, 28365, 28800, 29240,
  29685, 30135, 30589, 31049, 31512, 31981, 32455, 32933, 33417, 33905, 34399, 34897,
  35400, 35909, 36422, 36941, 37465, 37994, 38528, 39068, 39612, 40162, 40718, 41278,
  41844, 42416, 42993, 43575, 44163, 44756, 45355, 45960, 46570, 47186, 47807, 48435,
  49068, 49706, 50351, 51001, 51657, 52319, 52987, 53661, 54341, 55027, 55719, 56417,
  57121, 57832, 58548, 59271, 60000,
};

const uint16_t mod_mi_lut_gravity[MOD_MI_LUT_SIZE] = {
  33140, 31065, 29132, 27330, 25650, 24084, 22621, 21256, 19981, 18790, 17676, 16634,
  15660, 14748, 13894, 13094, 12344, 11642, 10983, 10365, 9785, 9240, 8729, 8249,
  7797, 7373, 6973, 6598, 6244, 5912, 5598, 5303, 5025, 4763, 4516, 4283,
  4063, 3855, 3659, 3474, 3299, 3134, 2978, 2830, 2690, 2558, 2433, 2315,
  2203, 2097, 1996, 1901, 1811, 1725, 1644, 1567, 1494, 1425, 1359, 1297,
  1237, 1181, 1127, 1077, 1028, 982, 938, 897, 857, 820, 784, 750,
  717, 686, 657, 629, 602, 576, 552, 529, 506, 485, 465, 446,
  427, 410, 393, 377, 362, 347, 333, 320, 307, 295, 283, 272,
  261, 251, 241, 232, 223, 214, 206, 198, 191, 183, 176, 170,
  163, 157, 151, 146, 140, 135, 130, 125, 121, 116, 112, 108,
  104, 100, 97, 93, 90, 87, 84, 81, 78, 75, 73, 70,
  68, 65, 63, 61, 59, 57, 55, 53, 51, 50, 48, 46,
  45, 43, 42, 40, 39, 38, 37, 35, 34, 33, 32, 31,
  30, 29, 28, 27, 26, 25, 25, 24, 23, 22, 22, 21,
  20, 20, 19, 19, 18, 17, 17, 16, 16, 15, 15, 14,
  14, 14, 13, 13, 12, 12, 12, 11, 11, 11, 10, 10,
  10, 9, 9, 9, 9, 8, 8, 8, 8, 7, 7, 7,
  7, 7, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5,
  5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3,
  3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2,
  2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
  2, 2, 1, 1, 1,
};

const mod_mi_scale_t mod_mi_scales[MOD_MI_SCALES] = {
  { 0, 0, 0, { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* Off */
  { 1536, 12, 0, { 0, 128, 256, 384, 512, 640, 768, 896, 1024, 1152, 1280, 1408, 0, 0, 0, 0 } },  /* Semitones */
  { 1536, 7, 0, { 0, 256, 512, 640, 896, 1152, 1408, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* Ionian (From midipal/BitT source code) */
  { 1536, 7, 0, { 0, 256, 384, 640, 896, 1152, 1280, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* Dorian (From midipal/BitT source code) */
  { 1536, 7, 0, { 0, 128, 384, 640, 896, 1024, 1280, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* Phrygian (From midipal/BitT source code) */
  { 1536, 7, 0, { 0, 256, 512, 768, 896, 1152, 1408, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* Lydian (From midipal/BitT source code) */
  { 1536, 7, 0, { 0, 256, 512, 640, 896, 1152, 1280, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* Mixolydian (From midipal/BitT source code) */
  { 1536, 7, 0, { 0, 256, 384, 640, 896, 1024, 1280, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* Aeolian (From midipal/BitT source code) */
  { 1536, 7, 0, { 0, 128, 384, 640, 768, 1024, 1280, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* Locrian (From midipal/BitT source code) */
  { 1536, 6, 0, { 0, 384, 512, 896, 1152, 1280, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* Blues major (From midipal/BitT source code) */
  { 1536, 6, 0, { 0, 384, 640, 768, 896, 1280, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* Blues minor (From midipal/BitT source code) */
  { 1536, 5, 0, { 0, 256, 512, 896, 1152, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* Pentatonic major (From midipal/BitT source code) */
  { 1536, 5, 0, { 0, 384, 640, 896, 1280, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* Pentatonic minor (From midipal/BitT source code) */
  { 1536, 8, 0, { 0, 128, 384, 512, 640, 896, 1024, 1280, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* Folk (From midipal/BitT source code) */
  { 1536, 5, 0, { 0, 128, 640, 896, 1024, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* Japanese (From midipal/BitT source code) */
  { 1536, 5, 0, { 0, 128, 384, 896, 1024, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* Gamelan (From midipal/BitT source code) */
  { 1536, 7, 0, { 0, 256, 384, 768, 896, 1024, 1408, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* Gypsy */
  { 1536, 7, 0, { 0, 128, 512, 640, 896, 1024, 1408, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* Arabian */
  { 1536, 7, 0, { 0, 128, 512, 640, 896, 1024, 1280, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* Flamenco */
  { 1536, 6, 0, { 0, 256, 512, 768, 1024, 1280, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* Whole tone (From midipal/BitT source code) */
  { 1536, 12, 0, { 0, 115, 261, 376, 522, 637, 783, 899, 1014, 1160, 1275, 1421, 0, 0, 0, 0 } },  /* pythagorean (From yarns source code) */
  { 1536, 12, 0, { 0, 128, 256, 384, 448, 640, 768, 896, 1024, 1152, 1280, 1344, 0, 0, 0, 0 } },  /* 1_4_eb (From yarns source code) */
  { 1536, 12, 0, { 0, 128, 256, 384, 448, 640, 768, 896, 1024, 1152, 1280, 1408, 0, 0, 0, 0 } },  /* 1_4_e (From yarns source code) */
  { 1536, 12, 0, { 0, 128, 256, 384, 448, 640, 768, 896, 1024, 1088, 1280, 1408, 0, 0, 0, 0 } },  /* 1_4_ea (From yarns source code) */
  { 1536, 7, 0, { 0, 115, 494, 637, 899, 1014, 1393, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* bhairav (From yarns source code) */
  { 1536, 5, 0, { 0, 143, 637, 899, 1042, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* gunakri (From yarns source code) */
  { 1536, 6, 0, { 0, 143, 494, 755, 1132, 1393, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* marwa (From yarns source code) */
  { 1536, 7, 0, { 0, 115, 494, 755, 899, 1014, 1393, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* shree (From yarns source code) */
  { 1536, 7, 0, { 0, 143, 494, 755, 899, 1042, 1393, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* purvi (From yarns source code) */
  { 1536, 7, 0, { 0, 261, 494, 637, 899, 1160, 1393, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* bilawal (From yarns source code) */
  { 1536, 7, 0, { 0, 261, 522, 783, 899, 1160, 1421, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* yaman (From yarns source code) */
  { 1536, 7, 0, { 0, 233, 376, 637, 899, 1132, 1275, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* kafi (From yarns source code) */
  { 1536, 7, 0, { 0, 261, 404, 637, 899, 1160, 1303, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* bhimpalasree (From yarns source code) */
  { 1536, 7, 0, { 0, 261, 376, 637, 899, 1014, 1275, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* darbari (From yarns source code) */
  { 1536, 7, 0, { 0, 261, 494, 637, 899, 1132, 1275, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* rageshree (From yarns source code) */
  { 1536, 8, 0, { 0, 261, 494, 637, 899, 1160, 1275, 1421, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* khamaj (From yarns source code) */
  { 1536, 8, 0, { 0, 261, 376, 637, 899, 1132, 1275, 1393, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* mimal (From yarns source code) */
  { 1536, 6, 0, { 0, 115, 376, 637, 1132, 1275, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* parameshwari (From yarns source code) */
  { 1536, 6, 0, { 0, 261, 376, 637, 899, 1393, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* rangeshwari (From yarns source code) */
  { 1536, 6, 0, { 0, 494, 637, 899, 1014, 1275, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* gangeshwari (From yarns source code) */
  { 1536, 6, 0, { 0, 261, 755, 899, 1132, 1275, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* kameshwari (From yarns source code) */
  { 1536, 7, 0, { 0, 261, 376, 637, 899, 1160, 1275, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* pa__kafi (From yarns source code) */
  { 1536, 7, 0, { 0, 261, 494, 637, 899, 1014, 1393, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* natbhairav (From yarns source code) */
  { 1536, 6, 0, { 0, 261, 522, 637, 1014, 1275, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* m_kauns (From yarns source code) */
  { 1536, 5, 0, { 0, 115, 637, 899, 1275, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* bairagi (From yarns source code) */
  { 1536, 5, 0, { 0, 115, 376, 899, 1275, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* b_todi (From yarns source code) */
  { 1536, 5, 0, { 0, 376, 637, 899, 1275, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* chandradeep (From yarns source code) */
  { 1536, 5, 0, { 0, 376, 637, 755, 1014, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* kaushik_todi (From yarns source code) */
  { 1536, 6, 0, { 0, 376, 494, 637, 1132, 1275, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },  /* jogeshwari (From yarns source code) */
};
