/* acid_gen.c -- "Acid Gen", a MIDI effect that plays acid lines: TB-3PO, the
 * generator of 303 lines in fm1-x0x (Charles Vestal, GPL-3.0-only;
 * third_party/fm1-x0x/seq/tb3po.c), which ports schwung-tb3po and, through
 * it, the TB_3PO applet of the Phazerville Hemisphere Suite (djphazer and
 * contributors, GPL-3.0). An engine API v3 MIDI effect (FM1_KIND_MIDI_FX,
 * fm1_engine.h) for the MIDI-FX slot in front of a sound, made for Acid Bass
 * (src/acid_bass.cc) and fine in front of any sound. It links GPL code, so
 * it is built only while the GPL switch is on (FM1_GPL_MODS, engines/Makefile;
 * mk/fm1-x0x.mk) and listed GPL in the licence table (src/registry.cc).
 *
 * The line. TB-3PO writes up to 32 steps from a seed: on each step a rest
 * (1 - Density), else a note of the scale within Octaves octaves, the root
 * often on the beat, an accent or a slide by their chances; a slide into a
 * rest is dropped. Mutations re-rolls about a quarter of the steps that many
 * times, continuing the line's own random stream, so the line is a function
 * of the parameters alone: a project saves it as its seed and mutation
 * count. Any change of Density, Accent, Slide, Octaves, Root, Scale,
 * Octave, Length, Seed or Mutations rebuilds it, from the same seed, at the
 * next step. Mut Every re-rolls once more every that many passes of the
 * line while it plays (X0X's auto-mutate), until Start or a rebuild.
 *
 * Playing it, as fm1-x0x's sequencer plays a 303 part (seq/sequencer.c,
 * fire_bass), on the host's 96-PPQN ticks: a step every 24 ticks (1/16), 16
 * (1/16T), 12 (1/32) or 32 (1/8T), forward, reverse, ping-pong or random. A
 * note holds for half its step; a step that slides holds into the next one,
 * whose note-on comes first and the held note's note-off one tick later, so
 * a 303 that takes legato as a slide (Acid Bass, schwung-303) slides. A
 * slide into the same note is a tie: nothing is sent. An accented step is
 * velocity 118, a plain one 72 (TB-3PO's and schwung-303's numbers: Acid
 * Bass accents from 100).
 *
 * The keys. Keys = Transpose (the default): the line plays while a key is
 * held, from step 1 when the first key goes down, in the newest key's
 * pitch: the line's root note (Octave, Root) moves to that key. Let go and
 * it stops, unless Latch is on. Keys = Run: the line plays while the host's
 * transport runs, from step 1 at Start; a held key transposes it the same
 * way, and none plays its own key. The keys themselves never sound. Root and
 * Scale may follow the project's key (Project), Major or Minor; a
 * chromatic project key plays Minor.
 *
 * The contract (fm1_engine.h, "MIDI effects"): time is ticks, never
 * samples, so the output is the same at any host block size; every note-on
 * gets exactly one note-off, which is never dropped (one that does not fit
 * goes out at the start of the next call), and a note-on that does not fit
 * is not sent; at a frame, note-offs first; FLUSH ends the notes it sounds,
 * PANIC also forgets the keys, RESET (Start) starts the line again from
 * step 1, rebuilt. No allocation, no libm, no stdio.
 *
 * MIT licence (this file); the program it is linked into is GPL-3.0 while
 * TB-3PO is in it.
 */
#include "fm1_engine.h"
#include "fm1_gpl_mods.h"   /* FM1_GPL_MODS, generated by engines/Makefile */

#include "seq/tb3po.h"

#include <string.h>

#if !FM1_GPL_MODS
#error "acid_gen.c links GPL code: it is built only with FM1_GPL_MODS=1 (engines/mk/fm1-x0x.mk)"
#endif

enum {
  AG_DENSITY, AG_ACCENT, AG_SLIDE, AG_OCTAVES,      /* LINE */
  AG_ROOT, AG_SCALE, AG_OCTAVE, AG_KEYS,            /* KEY */
  AG_RATE, AG_LENGTH, AG_DIRECTION, AG_LATCH,       /* PLAY */
  AG_SEED, AG_MUTATIONS, AG_MUT_EVERY,              /* SEED */
  AG_P_COUNT
};
enum { AG_KEYS_TRANSPOSE, AG_KEYS_RUN };
enum { AG_PROJECT = 0 };                            /* Root's and Scale's first entry */

static const char *const kOctaves[3] = { "1", "2", "3" };
static const char *const kRoots[13] = { "Project", "C", "C#", "D", "D#", "E", "F", "F#", "G", "G#",
                                        "A", "A#", "B" };
/* "Project", then TB-3PO's scales in its order (tb3po.c, SCALES). */
static const char *const kScales[1 + TB3PO_NSCALES] = { "Project", "Minor", "Phrygian", "Harm Minor",
                                                        "Min Pent", "Dorian", "Major" };
static const char *const kOctave[5] = { "0", "1", "2", "3", "4" };
static const char *const kKeys[2] = { "Transpose", "Run" };
/* X0X's RATE_16, RATE_16T, RATE_32 and RATE_8T (seq/pattern.h). */
static const char *const kRates[NRATES] = { "1/16", "1/16T", "1/32", "1/8T" };
static const uint8_t kRateTicks[NRATES] = { 24, 16, 12, 32 };
/* X0X's DIR_FWD, DIR_REV, DIR_PINGPONG and DIR_RANDOM. */
static const char *const kDirections[NDIRS] = { "Forward", "Reverse", "Ping-Pong", "Random" };
static const char *const kOffOn[2] = { "Off", "On" };

/* Every parameter is read at the next step (or rebuilds the line for the
 * next step): LATCH, and MOD for the numbers, as the arpeggiator's. Uids are
 * the index plus 1 and never change. The defaults are TB-3PO's: 70 / 40 /
 * 25 %, two octaves, A minor from A1, 16 steps of 1/16, seed 0xBEEF. */
#define L FM1_PARAM_LATCH
#define LM (FM1_PARAM_LATCH | FM1_PARAM_MOD)
enum { PAGE_LINE, PAGE_KEY, PAGE_PLAY, PAGE_SEED };
static const fm1_param_t kParams[AG_P_COUNT] = {
  { "Density", FM1_PARAM_FLOAT, 0, 100, 70, NULL, PAGE_LINE, 1, LM, FM1_UNIT_PCT, "DENS" },
  { "Accent", FM1_PARAM_FLOAT, 0, 100, 40, NULL, PAGE_LINE, 2, LM, FM1_UNIT_PCT, "ACC" },
  { "Slide", FM1_PARAM_FLOAT, 0, 100, 25, NULL, PAGE_LINE, 3, LM, FM1_UNIT_PCT, "SLD" },
  { "Octaves", FM1_PARAM_ENUM, 0, 2, 1, kOctaves, PAGE_LINE, 4, L, FM1_UNIT_NONE, "OCTS" },
  { "Root", FM1_PARAM_ENUM, 0, 12, 10, kRoots, PAGE_KEY, 5, L, FM1_UNIT_NONE, "ROOT" },
  { "Scale", FM1_PARAM_ENUM, 0, TB3PO_NSCALES, 1, kScales, PAGE_KEY, 6, L, FM1_UNIT_NONE, "SCALE" },
  { "Octave", FM1_PARAM_ENUM, 0, 4, 1, kOctave, PAGE_KEY, 7, L, FM1_UNIT_NONE, "OCT" },
  { "Keys", FM1_PARAM_ENUM, 0, 1, 0, kKeys, PAGE_KEY, 8, L, FM1_UNIT_NONE, "KEYS" },
  { "Rate", FM1_PARAM_ENUM, 0, NRATES - 1, 0, kRates, PAGE_PLAY, 9, L, FM1_UNIT_NONE, "RATE" },
  { "Length", FM1_PARAM_FLOAT, 1, NSTEPS, 16, NULL, PAGE_PLAY, 10, LM, FM1_UNIT_NONE, "LEN" },
  { "Direction", FM1_PARAM_ENUM, 0, NDIRS - 1, 0, kDirections, PAGE_PLAY, 11, L, FM1_UNIT_NONE, "DIR" },
  { "Latch", FM1_PARAM_ENUM, 0, 1, 0, kOffOn, PAGE_PLAY, 12, L, FM1_UNIT_NONE, "LTCH" },
  { "Seed", FM1_PARAM_FLOAT, 0, 65535, 48879, NULL, PAGE_SEED, 13, LM, FM1_UNIT_NONE, "SEED" },
  { "Mutations", FM1_PARAM_FLOAT, 0, 255, 0, NULL, PAGE_SEED, 14, LM, FM1_UNIT_NONE, "MUTS" },
  { "Mut Every", FM1_PARAM_FLOAT, 0, 16, 0, NULL, PAGE_SEED, 15, LM, FM1_UNIT_NONE, "MUTEV" },
};
#undef L
#undef LM

#define AG_MAX_KEYS 16  /* held keys, newest last */
#define AG_OWED 8       /* note-offs owed to the next call */
#define AG_VEL_ACCENT 118
#define AG_VEL_PLAIN 72

typedef struct acid_gen {
  int p[AG_P_COUNT];            /* each parameter as an integer */
  bpart_t line;                 /* the line TB-3PO wrote (pattern.h) */
  uint32_t mut_rng;             /* its random stream, after the mutations */
  uint32_t dir_rng;             /* the random direction's stream */
  int auto_done;                /* mutations Mut Every made since Start */
  int dirty;                    /* rebuild before the next step */
  int built_root, built_scale;  /* the key the line was built in */
  uint8_t keys[AG_MAX_KEYS];
  int n_keys;
  int playing;                  /* stepping */
  int latched;                  /* Transpose + Latch: playing with no key held */
  int transpose;                /* semitones the line plays at */
  int tick;                     /* ticks into the step; 0: a step is due */
  int pos;                      /* the step that played last, -1 none yet */
  int pp_dir;                   /* ping-pong's way, +1 or -1 */
  int passes;                   /* passes of the line since Start */
  int rand_steps;               /* steps in Random, a pass every Length of them */
  int sounding;                 /* the key sent and not yet ended, -1 none */
  int slides;                   /* it slides into the next step */
  int gate_left;                /* ticks until its note-off; -1: held to the next step */
  int slide_off;                /* a key to end at the next tick (a slide's), -1 none */
  uint8_t owed[AG_OWED];        /* note-offs that did not fit */
  int n_owed;
  uint8_t ctx_root, ctx_scale;  /* the project key, as the last call gave it */
} acid_gen_t;

/* ---- output ------------------------------------------------------------------------- */

typedef struct {
  fm1_midi_ev_t *ev;
  uint32_t cap, n;
} out_t;

static void send_off(acid_gen_t *s, out_t *o, uint16_t frame, int key) {
  if (key < 0) return;
  if (o->n < o->cap) {
    o->ev[o->n].frame = frame;
    o->ev[o->n].kind = FM1_MIDI_EV_NOTE_OFF;
    o->ev[o->n].a = (uint8_t)key;
    o->ev[o->n].b = 0;
    ++o->n;
  } else if (s->n_owed < AG_OWED) {
    s->owed[s->n_owed++] = (uint8_t)key;   /* at most two notes sound: room enough */
  }
}

static int send_on(out_t *o, uint16_t frame, int key, int vel) {
  if (o->n >= o->cap) return 0;            /* no room: not sent, so nothing to end */
  o->ev[o->n].frame = frame;
  o->ev[o->n].kind = FM1_MIDI_EV_NOTE_ON;
  o->ev[o->n].a = (uint8_t)key;
  o->ev[o->n].b = (uint16_t)vel;
  ++o->n;
  return 1;
}

/* Every note it sounds ends now. */
static void end_notes(acid_gen_t *s, out_t *o, uint16_t frame) {
  send_off(s, o, frame, s->slide_off);
  send_off(s, o, frame, s->sounding);
  s->slide_off = -1;
  s->sounding = -1;
  s->slides = 0;
  s->gate_left = -1;
}

/* ---- the line ------------------------------------------------------------------------ */

static int effective_root(const acid_gen_t *s) {
  return s->p[AG_ROOT] == AG_PROJECT ? s->ctx_root % 12 : s->p[AG_ROOT] - 1;
}

static int effective_scale(const acid_gen_t *s) {
  if (s->p[AG_SCALE] != AG_PROJECT) return s->p[AG_SCALE] - 1;
  return s->ctx_scale == FM1_KEY_MAJOR ? 5 : 0;      /* TB-3PO's Major, else Minor */
}

/* The line from the parameters, the project key and the mutations made. */
static void build(acid_gen_t *s) {
  tb3po_cfg_t *g = &s->line.gen;
  uint32_t r = 0;
  int k;
  memset(&s->line, 0, sizeof s->line);
  tb3po_defaults(g, (uint32_t)s->p[AG_SEED]);
  g->seed = (uint32_t)s->p[AG_SEED];       /* 0 is a seed too (tb3po_defaults maps it) */
  g->density = (uint8_t)s->p[AG_DENSITY];
  g->accent = (uint8_t)s->p[AG_ACCENT];
  g->slide = (uint8_t)s->p[AG_SLIDE];
  g->oct_range = (uint8_t)(s->p[AG_OCTAVES] + 1);
  g->root = (uint8_t)effective_root(s);
  g->scale = (uint8_t)effective_scale(s);
  g->base_oct = (uint8_t)s->p[AG_OCTAVE];
  g->mutate_bars = (uint8_t)s->p[AG_MUT_EVERY];
  s->line.len = (uint8_t)s->p[AG_LENGTH];
  s->line.rate = (uint8_t)s->p[AG_RATE];
  s->line.dir = (uint8_t)s->p[AG_DIRECTION];
  s->line.transpose = 24;
  tb3po_generate(&s->line);
  for (k = 0; k < s->p[AG_MUTATIONS] + s->auto_done; ++k) tb3po_mutate(&s->line, &r);
  s->mut_rng = r;
  s->built_root = g->root;
  s->built_scale = g->scale;
  s->dirty = 0;
}

/* The pitch the line's root plays at: the newest key held, or its own. */
static void retranspose(acid_gen_t *s) {
  const int own = 12 * (s->p[AG_OCTAVE] + 1) + effective_root(s);
  s->transpose = s->n_keys ? s->keys[s->n_keys - 1] - own : 0;
}

static uint32_t xorshift(uint32_t *r) {
  uint32_t x = *r ? *r : 1u;
  x ^= x << 13;
  x ^= x >> 17;
  x ^= x << 5;
  return *r = x;
}

/* The step after pos in the line's direction, and whether it starts a pass. */
static int next_step(acid_gen_t *s, int *wrapped) {
  const int len = s->line.len < 1 ? 1 : (s->line.len > NSTEPS ? NSTEPS : s->line.len);
  int n;
  *wrapped = 0;
  if (s->pos < 0) {                          /* the first step of a run */
    return s->line.dir == DIR_REV ? len - 1 : 0;
  }
  switch (s->line.dir) {
    case DIR_REV:
      n = (s->pos - 1 + len) % len;
      *wrapped = n == len - 1;
      return n;
    case DIR_PINGPONG:
      if (len == 1) {
        *wrapped = 1;
        return 0;
      }
      n = s->pos + s->pp_dir;
      if (n >= len || n < 0) {
        s->pp_dir = -s->pp_dir;
        n = s->pos + s->pp_dir;
      }
      *wrapped = n == 0;
      return n;
    case DIR_RANDOM:
      n = (int)(xorshift(&s->dir_rng) % (uint32_t)len);
      *wrapped = ++s->rand_steps % len == 0;   /* a pass is Length steps */
      return n;
    default:
      n = (s->pos + 1) % len;
      *wrapped = n == 0;
      return n;
  }
}

/* A step: its note-on (after the previous note's note-off, or before the
 * slid-from note's), its gate. */
static void fire(acid_gen_t *s, out_t *o, uint16_t frame) {
  int wrapped, note;
  const bstep_t *st;
  if (s->dirty) build(s);
  s->pos = next_step(s, &wrapped);
  if (wrapped) {
    ++s->passes;
    if (s->p[AG_MUT_EVERY] && s->passes % s->p[AG_MUT_EVERY] == 0) {   /* X0X's auto-mutate */
      ++s->auto_done;
      tb3po_mutate(&s->line, &s->mut_rng);
    }
  }
  st = &s->line.step[s->pos];
  if (bstep_gate(st) == G_REST) {
    end_notes(s, o, frame);
    return;
  }
  note = st->note + s->transpose;
  note = note < 0 ? 0 : (note > 127 ? 127 : note);
  if (s->sounding >= 0 && s->slides) {
    if (note != s->sounding) {               /* a slide: the new note first */
      if (send_on(o, frame, note, (st->flags & BS_ACCENT) ? AG_VEL_ACCENT : AG_VEL_PLAIN)) {
        s->slide_off = s->sounding;          /* its note-off at the next tick */
        s->sounding = note;
      } else {
        end_notes(s, o, frame);
        return;
      }
    }                                        /* the same note: a tie */
  } else {
    send_off(s, o, frame, s->sounding);
    s->sounding = -1;
    if (send_on(o, frame, note, (st->flags & BS_ACCENT) ? AG_VEL_ACCENT : AG_VEL_PLAIN)) {
      s->sounding = note;
    }
  }
  s->slides = (st->flags & BS_SLIDE) != 0;
  s->gate_left = s->slides ? -1 : kRateTicks[s->line.rate & 3] / 2;
}

/* ---- play ------------------------------------------------------------------------------ */

static int key_index(const acid_gen_t *s, int key) {
  int k;
  for (k = 0; k < s->n_keys; ++k) {
    if (s->keys[k] == key) return k;
  }
  return -1;
}

static void start(acid_gen_t *s) {
  s->playing = 1;
  s->tick = 0;
  s->pos = -1;
  s->pp_dir = 1;
  s->rand_steps = 0;
}

static void stop(acid_gen_t *s, out_t *o, uint16_t frame) {
  end_notes(s, o, frame);
  s->playing = 0;
  s->latched = 0;
}

static void key_down(acid_gen_t *s, int key, uint16_t frame, out_t *o) {
  int k = key_index(s, key);
  (void)o;
  (void)frame;
  if (k >= 0) {                              /* again: it becomes the newest */
    memmove(&s->keys[k], &s->keys[k + 1], (size_t)(s->n_keys - k - 1));
    --s->n_keys;
  }
  if (s->n_keys == AG_MAX_KEYS) {
    memmove(&s->keys[0], &s->keys[1], AG_MAX_KEYS - 1);
    --s->n_keys;
  }
  s->keys[s->n_keys++] = (uint8_t)key;
  retranspose(s);
  if (s->p[AG_KEYS] == AG_KEYS_TRANSPOSE && !s->playing) start(s);
  s->latched = 0;
}

static void key_up(acid_gen_t *s, int key, uint16_t frame, out_t *o) {
  const int k = key_index(s, key);
  if (k < 0) return;
  memmove(&s->keys[k], &s->keys[k + 1], (size_t)(s->n_keys - k - 1));
  --s->n_keys;
  if (s->n_keys) {
    retranspose(s);
    return;
  }
  if (s->p[AG_KEYS] != AG_KEYS_TRANSPOSE) {
    retranspose(s);                          /* Run: back to its own key */
    return;
  }
  if (s->p[AG_LATCH]) {
    s->latched = 1;                          /* plays on in the last key's pitch */
  } else {
    stop(s, o, frame);
  }
}

/* A tick: the slid-from note ends, a gate runs out, a step is due. */
static void on_tick(acid_gen_t *s, const fm1_midi_fx_ctx_t *ctx, uint16_t frame, out_t *o) {
  const int run = s->p[AG_KEYS] == AG_KEYS_RUN;
  if (s->slide_off >= 0) {
    send_off(s, o, frame, s->slide_off);
    s->slide_off = -1;
  }
  if (s->gate_left > 0 && --s->gate_left == 0) {
    send_off(s, o, frame, s->sounding);
    s->sounding = -1;
    s->gate_left = -1;
    s->slides = 0;
  }
  if (run) {
    const int running = ctx && ctx->running;
    if (!running) {
      if (s->playing) stop(s, o, frame);
      return;
    }
    if (!s->playing) start(s);
  }
  if (!s->playing) return;
  if (s->tick == 0) fire(s, o, frame);
  if (++s->tick >= kRateTicks[s->line.rate & 3]) s->tick = 0;
}

static void handle(acid_gen_t *s, const fm1_midi_ev_t *ev, out_t *o) {
  switch (ev->kind) {
    case FM1_MIDI_EV_NOTE_ON:
      if (ev->a > 127) break;
      if (ev->b) key_down(s, ev->a, ev->frame, o);
      else key_up(s, ev->a, ev->frame, o);
      break;
    case FM1_MIDI_EV_NOTE_OFF:
      if (ev->a <= 127) key_up(s, ev->a, ev->frame, o);
      break;
    case FM1_MIDI_EV_RESET:                  /* Start: the line again, from step 1 */
      s->auto_done = 0;
      s->passes = 0;
      s->dir_rng = (uint32_t)s->p[AG_SEED] * 2654435761u + 1u;
      s->dirty = 1;
      if (s->playing || s->p[AG_KEYS] == AG_KEYS_RUN) {
        end_notes(s, o, ev->frame);
        start(s);
      }
      break;
    case FM1_MIDI_EV_FLUSH:                  /* Stop, a bypass: the notes end */
      end_notes(s, o, ev->frame);
      if (s->p[AG_KEYS] == AG_KEYS_RUN || !s->n_keys) {
        s->playing = 0;
        s->latched = 0;
      }
      break;
    case FM1_MIDI_EV_PANIC:                  /* and the keys are forgotten */
      s->n_keys = 0;
      retranspose(s);
      stop(s, o, ev->frame);
      break;
    default:                                 /* SUSTAIN, STEP: nothing */
      break;
  }
}

/* ---- the effect ------------------------------------------------------------------------- */

static size_t ag_size(const fm1_host_t *host) {
  (void)host;
  return (sizeof(acid_gen_t) + 15u) & ~(size_t)15u;
}

static void *ag_create(void *mem, const fm1_host_t *host) {
  acid_gen_t *s = (acid_gen_t *)mem;
  int i;
  (void)host;
  if (!s) return NULL;
  memset(s, 0, sizeof *s);
  for (i = 0; i < AG_P_COUNT; ++i) s->p[i] = (int)(kParams[i].def + 0.5f);
  s->ctx_root = 0;
  s->ctx_scale = FM1_KEY_MAJOR;
  s->dir_rng = (uint32_t)s->p[AG_SEED] * 2654435761u + 1u;
  s->pos = -1;
  s->pp_dir = 1;
  s->sounding = s->slide_off = -1;
  s->gate_left = -1;
  build(s);
  retranspose(s);
  return s;
}

static void ag_destroy(void *self) { (void)self; }

static void ag_set_param(void *self, uint16_t index, float value) {
  acid_gen_t *s = (acid_gen_t *)self;
  int v;
  if (!s || index >= AG_P_COUNT) return;
  value = fm1_param_clamp(&kParams[index], value);
  v = (int)(value + 0.5f);
  if (v == s->p[index]) return;
  s->p[index] = v;
  switch (index) {
    case AG_KEYS:
    case AG_LATCH:
      break;                                 /* read at the next key or tick */
    case AG_SEED:
      s->dir_rng = (uint32_t)v * 2654435761u + 1u;
      s->dirty = 1;
      break;
    default:
      s->dirty = 1;                          /* the line, rebuilt at the next step */
      break;
  }
  if (index == AG_ROOT || index == AG_OCTAVE) retranspose(s);
}

static uint32_t ag_process(void *self, const fm1_midi_ev_t *in, uint32_t n_in,
                           const fm1_midi_fx_ctx_t *ctx, fm1_midi_ev_t *out, uint32_t cap) {
  acid_gen_t *s = (acid_gen_t *)self;
  out_t o;
  uint32_t i = 0, j = 0, k;
  const uint32_t n_ticks = ctx && ctx->ticks ? ctx->n_ticks : 0u;
  if (!s) return 0;
  if (!in) n_in = 0;
  o.ev = out;
  o.cap = out ? cap : 0u;
  o.n = 0;
  /* Note-offs owed from the last call first, at its first frame. */
  for (k = 0; k < (uint32_t)s->n_owed && o.n < o.cap; ++k) {
    o.ev[o.n].frame = 0;
    o.ev[o.n].kind = FM1_MIDI_EV_NOTE_OFF;
    o.ev[o.n].a = s->owed[k];
    o.ev[o.n].b = 0;
    ++o.n;
  }
  if (k) {
    memmove(&s->owed[0], &s->owed[k], (size_t)(s->n_owed - (int)k));
    s->n_owed -= (int)k;
  }
  /* The project key: a line in it is rebuilt when it moves. */
  if (ctx && (ctx->key_root != s->ctx_root || ctx->key_scale != s->ctx_scale)) {
    s->ctx_root = ctx->key_root;
    s->ctx_scale = ctx->key_scale;
    if (effective_root(s) != s->built_root || effective_scale(s) != s->built_scale) s->dirty = 1;
    retranspose(s);
  }
  /* Inputs and ticks by frame; at one frame the inputs come first, so a key
   * pressed on a tick plays on it. */
  while (i < n_in || j < n_ticks) {
    if (i < n_in && (j >= n_ticks || in[i].frame <= ctx->ticks[j])) {
      handle(s, &in[i++], &o);
    } else {
      on_tick(s, ctx, ctx->ticks[j++], &o);
    }
  }
  return o.n;
}

const fm1_midi_fx_t fm1_midi_fx_acid_gen = {
  {
    FM1_ENGINE_MAGIC, FM1_ENGINE_API_VERSION, FM1_KIND_MIDI_FX,
    "acid-gen", "Acid Gen",
    "Acid lines from TB-3PO, the generator in fm1-x0x by Charles Vestal (GPL-3.0), after "
    "schwung-tb3po and the Phazerville Hemisphere Suite's TB_3PO applet by djphazer and "
    "contributors (GPL-3.0)",
    kParams, AG_P_COUNT, 0,
    ag_size, ag_create, ag_destroy,
    NULL, NULL, NULL,         /* notes come through process() */
    ag_set_param, NULL,       /* no audio */
    NULL,                     /* no per-note offsets */
    0, NULL,                  /* no effect extension */
    0, 0,                     /* not a pad kit */
  },
  ag_process,
};
