/* registry.c -- the MIDI effects' static registry (engine API v3,
 * FM1_KIND_MIDI_FX; fm1_engine.h). Its own list, beside the engines' in
 * src/registry.cc, so the sound and effect lists stay as they are. Adding a
 * MIDI effect is a line here and its sources in mk/midi_fx.mk. A GPL MIDI
 * effect's line goes under #if FM1_GPL_MODS (the GPL switch, engines/Makefile)
 * with its sources in its own fragment, and its licence row in
 * src/registry.cc's table.
 * MIT licence, like the rest of this repository.
 */
#include "fm1_engine.h"
#include "fm1_gpl_mods.h"   /* FM1_GPL_MODS, generated by engines/Makefile */

#include <string.h>

#if !defined(FM1_GPL_MODS) || (FM1_GPL_MODS != 0 && FM1_GPL_MODS != 1)
#error "FM1_GPL_MODS must be 0 or 1 (engines/Makefile)"
#endif

extern const fm1_midi_fx_t fm1_midi_fx_arp;
#if FM1_GPL_MODS
/* GPL MIDI effects (built by their own fragments). */
extern const fm1_midi_fx_t fm1_midi_fx_acid_gen;   /* fm1-x0x's TB-3PO (mk/fm1-x0x.mk) */
#endif

const fm1_midi_fx_t *const fm1_midi_fxs[] = {
  &fm1_midi_fx_arp,
#if FM1_GPL_MODS
  &fm1_midi_fx_acid_gen,
#endif
};
const size_t fm1_midi_fx_count = sizeof(fm1_midi_fxs) / sizeof(fm1_midi_fxs[0]);

const fm1_midi_fx_t *fm1_midi_fx_find(const char *id) {
  size_t i;
  for (i = 0; id && i < fm1_midi_fx_count; ++i) {
    if (strcmp(fm1_midi_fxs[i]->engine.id, id) == 0) return fm1_midi_fxs[i];
  }
  return NULL;
}
