"""Mathematically reconstructed FM-1 DSP lookup tables and scalar oracle.

The tables are generated from formulas, not distributed vendor firmware bytes.
The scalar model covers the log-sine/exponent stage only, not a full voice or
DSP emulator. See docs/16-operator-mathematics.md for byte-level evidence.
"""

from functools import lru_cache
import hashlib
import math
import struct


TABLE_SIZE = 1024
MAX_IMAGE_SIZE = 16 * 1024 * 1024
MAX_TABLE_MATCHES = 64


@lru_cache(maxsize=1)
def exponent_table() -> tuple[int, ...]:
    """Fractional 2**x mantissa, 10 fraction bits and 12 output fraction bits."""
    return tuple(round((2 ** (i / TABLE_SIZE) - 1) * 4096) for i in range(TABLE_SIZE))


@lru_cache(maxsize=1)
def log_sine_table() -> tuple[int, ...]:
    """Quarter-wave -log2(sin), sampled at cell centers, 10 fraction bits."""
    return tuple(round(-math.log2(math.sin((i + 0.5) * math.pi / (2 * TABLE_SIZE)))
                       * TABLE_SIZE) for i in range(TABLE_SIZE))


def _float32(value: float) -> float:
    return struct.unpack("<f", struct.pack("<f", value))[0]


@lru_cache(maxsize=1)
def modulation_sine_table() -> tuple[float, ...]:
    """512-cell sine plus endpoint, rounded to eight decimal places then f32.

    Use quadrant symmetry to make the zero signs and endpoints independent of
    the host libm's approximation to sin(pi). The endpoint is negative zero.
    """
    quarter = tuple(_float32(round(math.sin(i * math.pi / 256), 8)) for i in range(129))
    positive = quarter + quarter[-2::-1]
    return positive + tuple(-value for value in positive[1:])


@lru_cache(maxsize=1)
def hyperbolic_tangent_table() -> tuple[float, ...]:
    """513 float32 entries for tanh(i/64), including both domain endpoints."""
    return tuple(_float32(math.tanh(i / 64)) for i in range(513))


def _runtime_address(offset, size, regions):
    for region in regions:
        start, address = region.get("file_offset"), region.get("runtime_address")
        if (type(start) is int and type(address) is int and start <= offset
                and offset + size <= start + region["size"]):
            return address + offset - start
    return None


def analyze_dsp_tables(blob: bytes, regions=()) -> dict:
    """Locate full formula-generated tables; short prefixes never count."""
    if not isinstance(blob, bytes) or not 0 < len(blob) <= MAX_IMAGE_SIZE:
        raise ValueError("application must contain 1 to 16 MiB")
    definitions = [
        ("fractional_exponent", exponent_table(), "H", "uint16 little-endian", "round((2**(i/1024) - 1) * 4096)"),
        ("quarter_wave_log_sine", log_sine_table(), "H", "uint16 little-endian", "round(-log2(sin((i + 0.5) * pi / 2048)) * 1024)"),
        ("modulation_sine", modulation_sine_table(), "f", "float32 little-endian", "float32(round(sin(2*pi*i/512), 8)); signed endpoint -0.0"),
        ("hyperbolic_tangent", hyperbolic_tangent_table(), "f", "float32 little-endian", "float32(tanh(i/64))"),
    ]
    tables = []
    truncated = []
    for name, values, format_code, entry_type, formula in definitions:
        encoded = struct.pack(f"<{len(values)}{format_code}", *values)
        position = 0
        count = 0
        while count < MAX_TABLE_MATCHES:
            offset = blob.find(encoded, position)
            if offset < 0:
                break
            count += 1
            tables.append({"name": name, "file_offset": offset, "size": len(encoded),
                           "address": _runtime_address(offset, len(encoded), regions),
                           "entries": len(values), "entry_type": entry_type, "formula": formula,
                           "sha256": hashlib.sha256(encoded).hexdigest(),
                           "confidence": "verified full mathematical table match",
                           "matching_entries": len(values), "byte_exact": True,
                           **({"maximum_integer_error": 0} if format_code == "H" else {}),
                           "evidence": f"All {len(values)} entries match independently generated bytes, including float zero signs; no prefix-only identification."})
            position = offset + len(encoded)
        if count == MAX_TABLE_MATCHES and blob.find(encoded, position) >= 0:
            truncated.append(name)
    pairs = []
    for exponential in (t for t in tables if t["name"] == "fractional_exponent"):
        for sine in (t for t in tables if t["name"] == "quarter_wave_log_sine"):
            if sine["file_offset"] == exponential["file_offset"] + exponential["size"]:
                pairs.append({"exponent_file_offset": exponential["file_offset"],
                              "log_sine_file_offset": sine["file_offset"],
                              "size": 4096, "evidence": "Adjacent complete formula-generated lookup tables."})
    return {"tables": tables, "adjacent_pairs": pairs, "truncated_tables": truncated,
            "sample_model": "log_sine_lookup_stage",
            "limits": ["Table matches alone do not locate or prove execution of a DSP routine.",
                       "The scalar model excludes voice envelopes, gain interpolation, feedback, operator routing, mixing and effects.",
                       "No hardware waveform equivalence is established."],
            "device_io_performed": False}


def log_sine_lookup_stage(phase: int, attenuation: int) -> int:
    """Derived integer lookup stage in the inspected operator path.

    phase: 24-bit phase/modulation sum; 4096 table cells per turn (low12 bits
    discarded). attenuation: nonnegative log2 attenuation, 1024 units/octave.
    Output is the signed 19-bit representative before <<13, not the unsigned
    register value. Negative half-cycle uses one's complement. Shifting this
    result left by 13 modulo 32 bits matches the inspected output conversion.
    This is an offline reference model, not a device emulator.
    """
    if type(phase) is not int or type(attenuation) is not int or not 0 <= attenuation <= 16384:
        raise ValueError("phase must be an integer; attenuation must be in 0..16384")
    position = (phase & 0xFFFFFF) >> 12
    index = position & 1023
    if position & 1024:
        index ^= 1023
    logarithm = log_sine_table()[index] + attenuation
    mantissa = exponent_table()[(~logarithm) & 1023] + 4096
    magnitude = mantissa >> ((logarithm >> 10) & 31)
    return -magnitude - 1 if position & 2048 else magnitude
