#!/usr/bin/env python3
"""msfa's start-up tables, made ahead of time: the FM6 engine's sine, exp2
and frequency tables as const data, written into engines/src/msfa_rom.cc.

    python3 tools/msfa_tables.py            # rewrite engines/src/msfa_rom.cc
    python3 tools/msfa_tables.py --check    # exit 1 if the file is stale

msfa (Google's music-synthesizer-for-android, Apache-2.0, vendored in
engines/third_party/msfa) fills three tables in RAM when it starts:
Sin::init (sin.cc), Exp2::init (exp2.cc) and Freqlut::init (freqlut.cc).
Each takes one libm value (cos and sin of 2 pi / 1024, 2^(1/1024)) and then
integer steps or repeated multiplication in doubles. This tool runs the same
steps, with those libm values computed correctly rounded (Decimal), so the
tables come out as msfa's own init makes them on any machine whose libm is
right in the last bit; fm1-dx7-oracle --tables-vs-msfa compares them with
msfa's init, word for word (tests/test_engines_dx7.py). The frequency table
depends on the rate; this file holds it at the FM-1's 44,118 Hz, and the
engine fills one in its instance at any other rate (engines/msfa.md,
"Tables in flash").

The values are mathematical constants in msfa's fixed-point formats, not
code; the file is MIT like the rest of this repository.
"""
from __future__ import annotations

import argparse
import math
import sys
from decimal import Decimal, getcontext
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "engines" / "src" / "msfa_rom.cc"
FM1_RATE = 44118             # the FM-1's rate: the frequency table held as const data
SIN_N = 1024                 # SIN_N_SAMPLES, EXP2_N_SAMPLES, Freqlut's N_SAMPLES

getcontext().prec = 60
PI = Decimal("3.14159265358979323846264338327950288419716939937510582097494")


def dsin(x: Decimal) -> Decimal:
    term, total, k = x, x, 1
    while abs(term) > Decimal(10) ** -55:
        term = -term * x * x / ((2 * k) * (2 * k + 1))
        total += term
        k += 1
    return total


def dcos(x: Decimal) -> Decimal:
    term, total, k = Decimal(1), Decimal(1), 1
    while abs(term) > Decimal(10) ** -55:
        term = -term * x * x / ((2 * k - 1) * (2 * k))
        total += term
        k += 1
    return total


# 2^(1/1024), correctly rounded to a double: exp2(1.0 / 1024) in Exp2::init
# and pow(2, 1.0 / 1024) in Freqlut::init, which the compilers fold.
INC = float((Decimal(2).ln() / SIN_N).exp())


def sin_table() -> list[int]:
    """Sin::init with SIN_DELTA: 1,024 points of a Q24 sine in the odd
    entries, each one's step to the next in the even ones."""
    dphase = float(2 * PI / SIN_N)                    # 2 * M_PI / SIN_N_SAMPLES, a double
    c = math.floor(float(dcos(Decimal(dphase))) * (1 << 30) + 0.5)
    s = math.floor(float(dsin(Decimal(dphase))) * (1 << 30) + 0.5)
    u, v, r = 1 << 30, 0, 1 << 29
    tab = [0] * (2 * SIN_N)
    for i in range(SIN_N // 2):
        tab[2 * i + 1] = (v + 32) >> 6
        tab[2 * (i + SIN_N // 2) + 1] = -((v + 32) >> 6)
        t = (u * s + v * c + r) >> 30
        u = (u * c - v * s + r) >> 30
        v = t
    for i in range(SIN_N - 1):
        tab[2 * i] = tab[2 * i + 3] - tab[2 * i + 1]
    tab[2 * SIN_N - 2] = -tab[2 * SIN_N - 1]
    return tab


def exp2_table() -> list[int]:
    """Exp2::init: 2^(i / 1024) in Q30 in the odd entries, steps in the even
    ones; the last step reaches 2^31 (computed in 32 unsigned bits)."""
    y, tab = float(1 << 30), [0] * (2 * SIN_N)
    for i in range(SIN_N):
        tab[2 * i + 1] = math.floor(y + 0.5)
        y *= INC
    for i in range(SIN_N - 1):
        tab[2 * i] = tab[2 * i + 3] - tab[2 * i + 1]
    tab[2 * SIN_N - 2] = (1 << 31) - tab[2 * SIN_N - 1]
    return tab


def freq_table(rate: int) -> list[int]:
    """Freqlut::init(rate): 1,025 phase increments, an octave from
    2^44 / rate (logfreq 0, the top of msfa's 20 octaves)."""
    y, tab = float(1 << 44) / rate, []
    for _ in range(SIN_N + 1):
        tab.append(math.floor(y + 0.5))
        y *= INC
    return tab


def c_array(name: str, values: list[int], comment: str) -> str:
    lines = [f"// {comment}", f"extern const int32_t {name}[{len(values)}] = {{"]
    for i in range(0, len(values), 8):
        lines.append("  " + ", ".join(f"{v}" for v in values[i:i + 8]) + ",")
    lines.append("};")
    return "\n".join(lines) + "\n"


def source() -> str:
    head = f"""\
// msfa_rom.cc -- msfa's sine, exp2 and frequency tables as const data, which
// the FM-1 keeps in flash, for the FM6 engine (src/msfa_dx7.cc). Generated by
// tools/msfa_tables.py, which runs the steps of msfa's Sin::init, Exp2::init
// and Freqlut::init({FM1_RATE}) (third_party/msfa, Apache-2.0); do not edit.
// fm1-dx7-oracle --tables-vs-msfa checks them against msfa's own init, word
// for word. The values are msfa's fixed-point constants; MIT licence, like
// the rest of this repository. engines/msfa.md, "Tables in flash".

#include "msfa.h"   // the declarations these definitions must match

namespace fm1_msfa {{

"""
    body = "\n".join([
        c_array("kSinTab", sin_table(),
                "Sin::init (SIN_DELTA): odd entries a Q24 sine, even ones the step to the next."),
        c_array("kExp2Tab", exp2_table(),
                "Exp2::init: odd entries 2^(i / 1024) in Q30, even ones the step to the next."),
        c_array("kFreqLut44118", freq_table(FM1_RATE),
                f"Freqlut::init({FM1_RATE}): phase increments over an octave, 2^44 / rate up."),
    ])
    return head + body + "\n}  // namespace fm1_msfa\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="exit 1 if msfa_rom.cc is stale")
    a = ap.parse_args()
    text = source()
    if a.check:
        if not OUT.exists() or OUT.read_text() != text:
            print(f"{OUT} is stale: run tools/msfa_tables.py", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
