#!/usr/bin/env python3
"""Turn tools/font5x9.txt into src/fm1_font.h, the virtual FM-1's TFT font.

    python3 sim/web/tools/gen_font.py            # rewrite src/fm1_font.h
    python3 sim/web/tools/gen_font.py --check    # exit 1 if it is out of date

Each glyph is nine bytes, one per row, with bit 4 the leftmost of the five
columns. MIT licence, like the rest of this repository.
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE / "font5x9.txt"
OUT = HERE.parent / "src" / "fm1_font.h"
FIRST, LAST = 0x20, 0x7E
ROWS, COLS = 9, 5


def parse(text):
    glyphs, cur, name = {}, None, None
    for lineno, raw in enumerate(text.splitlines(), 1):
        line = raw.rstrip("\n")
        if line.startswith("#") and cur is None or not line.strip():
            continue
        if line.startswith("= "):
            name = line[2:]
            ch = " " if name == "space" else name
            if len(ch) != 1 or not FIRST <= ord(ch) <= LAST:
                raise SystemExit(f"{SRC.name}:{lineno}: bad glyph name {name!r}")
            if ch in glyphs:
                raise SystemExit(f"{SRC.name}:{lineno}: {name!r} defined twice")
            cur = glyphs[ch] = []
            continue
        if cur is None:
            raise SystemExit(f"{SRC.name}:{lineno}: row before any glyph")
        if len(line) != COLS or set(line) - set("#."):
            raise SystemExit(f"{SRC.name}:{lineno}: row {line!r} is not five of '#'/'.'")
        if len(cur) == ROWS:
            raise SystemExit(f"{SRC.name}:{lineno}: more than {ROWS} rows in {name!r}")
        cur.append(sum(1 << (COLS - 1 - i) for i, c in enumerate(line) if c == "#"))
    missing = [chr(c) for c in range(FIRST, LAST + 1) if chr(c) not in glyphs]
    if missing:
        raise SystemExit(f"{SRC.name}: no glyph for {''.join(missing)!r}")
    return {ch: rows + [0] * (ROWS - len(rows)) for ch, rows in glyphs.items()}


def render(glyphs):
    out = [
        "/* fm1_font.h -- generated by sim/web/tools/gen_font.py from font5x9.txt; do not",
        " * edit. Printable ASCII (0x20-0x7E), 5 x 9 cells, one byte per row, bit 4 the",
        " * leftmost column. Rows 0-6 capitals, 2-6 x-height, 7-8 descenders. MIT. */",
        "#ifndef FM1_FONT_H_",
        "#define FM1_FONT_H_",
        "",
        "#include <stdint.h>",
        "",
        f"#define FM1_FONT_FIRST 0x{FIRST:02X}",
        f"#define FM1_FONT_LAST 0x{LAST:02X}",
        f"#define FM1_FONT_COLS {COLS}",
        f"#define FM1_FONT_ROWS {ROWS}",
        "",
        f"static const uint8_t fm1_font5x9[{LAST - FIRST + 1}][{ROWS}] = {{",
    ]
    for c in range(FIRST, LAST + 1):
        ch = chr(c)
        rows = ", ".join(f"0x{r:02X}" for r in glyphs[ch])
        label = "space" if ch == " " else ("backslash" if ch == "\\" else ch)
        out.append(f"  {{ {rows} }},  /* {label} */")
    out += ["};", "", "#endif /* FM1_FONT_H_ */", ""]
    return "\n".join(out)


def main(argv):
    text = render(parse(SRC.read_text()))
    if "--check" in argv:
        if not OUT.exists() or OUT.read_text() != text:
            print(f"{OUT} is out of date; run {Path(__file__).name}", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
