#!/usr/bin/env python3
"""Write the virtual FM-1's TFT fonts as C headers in src/:

    fm1_font.h        MAIN: the hand-made 5 x 9 (tools/font5x9.txt), drawn at x2
    fm1_font_mid.h    MID: Spleen 8 x 16, drawn at x1
    fm1_font_small.h  SMALL: Spleen 6 x 12, drawn at x1

    python3 sim/web/tools/gen_font.py            # rewrite the three headers
    python3 sim/web/tools/gen_font.py --check    # exit 1 if one is out of date
    python3 sim/web/tools/gen_font.py --sizes    # each table's flash cost, as JSON

Each glyph is one byte a row, bit COLS-1 the leftmost column. The 5 x 9's
nine bytes a glyph keep every row of its cell. Spleen's tables keep only the
rows that some character taken here paints (the "box": a run's logged box in
fm1_tft.c is exactly what its characters can paint), so the 8 x 16 loses its
blank top and bottom rows. Spleen (sim/web/third_party/spleen/, Frederic
Cambus, BSD-2-Clause) is read from its BDF files, unmodified; the tables are
derived from them and keep that licence (third_party/spleen/UPSTREAM.md).
MIT licence for this script, like the rest of this repository.
"""
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE / "font5x9.txt"
OUT = HERE.parent / "src" / "fm1_font.h"
SPLEEN = HERE.parent / "third_party" / "spleen"
FIRST, LAST = 0x20, 0x7E
ROWS, COLS = 9, 5

# The Spleen faces: (macro prefix, array name, BDF, header). Only printable
# ASCII is taken: no string the screens draw has anything else [verified:
# every string literal in sim/web/src and engines/, 2026-10-06].
SPLEEN_FACES = (
    ("MID", "fm1_font_mid", SPLEEN / "spleen-8x16.bdf", HERE.parent / "src" / "fm1_font_mid.h"),
    ("SMALL", "fm1_font_small", SPLEEN / "spleen-6x12.bdf", HERE.parent / "src" / "fm1_font_small.h"),
)


def parse(text):
    glyphs, cur, name = {}, None, None
    for lineno, raw in enumerate(text.splitlines(), 1):
        line = raw.rstrip("\n")
        if line.startswith("#") and cur is None or not line.strip():
            continue
        if line.startswith("= "):
            name = line[2:]
            ch = " " if name == "space" else name
            if len(ch) != 1 or not FIRST <= ord(ch) <= LAST:
                raise SystemExit(f"{SRC.name}:{lineno}: bad glyph name {name!r}")
            if ch in glyphs:
                raise SystemExit(f"{SRC.name}:{lineno}: {name!r} defined twice")
            cur = glyphs[ch] = []
            continue
        if cur is None:
            raise SystemExit(f"{SRC.name}:{lineno}: row before any glyph")
        if len(line) != COLS or set(line) - set("#."):
            raise SystemExit(f"{SRC.name}:{lineno}: row {line!r} is not five of '#'/'.'")
        if len(cur) == ROWS:
            raise SystemExit(f"{SRC.name}:{lineno}: more than {ROWS} rows in {name!r}")
        cur.append(sum(1 << (COLS - 1 - i) for i, c in enumerate(line) if c == "#"))
    missing = [chr(c) for c in range(FIRST, LAST + 1) if chr(c) not in glyphs]
    if missing:
        raise SystemExit(f"{SRC.name}: no glyph for {''.join(missing)!r}")
    return {ch: rows + [0] * (ROWS - len(rows)) for ch, rows in glyphs.items()}


def label(c):
    ch = chr(c)
    return "space" if ch == " " else ("backslash" if ch == "\\" else ch)


def render(glyphs):
    out = [
        "/* fm1_font.h -- generated by sim/web/tools/gen_font.py from font5x9.txt; do not",
        " * edit. Printable ASCII (0x20-0x7E), 5 x 9 cells, one byte per row, bit 4 the",
        " * leftmost column. Rows 0-6 capitals, 2-6 x-height, 7-8 descenders. MIT. */",
        "#ifndef FM1_FONT_H_",
        "#define FM1_FONT_H_",
        "",
        "#include <stdint.h>",
        "",
        f"#define FM1_FONT_FIRST 0x{FIRST:02X}",
        f"#define FM1_FONT_LAST 0x{LAST:02X}",
        f"#define FM1_FONT_COLS {COLS}",
        f"#define FM1_FONT_ROWS {ROWS}",
        "",
        f"static const uint8_t fm1_font5x9[{LAST - FIRST + 1}][{ROWS}] = {{",
    ]
    for c in range(FIRST, LAST + 1):
        rows = ", ".join(f"0x{r:02X}" for r in glyphs[chr(c)])
        out.append(f"  {{ {rows} }},  /* {label(c)} */")
    out += ["};", "", "#endif /* FM1_FONT_H_ */", ""]
    return "\n".join(out)


# ---- Spleen: BDF in, the box's rows out -------------------------------------


def parse_bdf(path):
    """The font's properties and {code point: cell rows}, each glyph placed in
    the FONTBOUNDINGBOX cell (ascent rows above the baseline, descent below)
    as a list of rows of 0/1 pixels, left to right."""
    text = path.read_text(encoding="ascii")
    prop = lambda k: re.search(rf"^{k} (.+)$", text, re.M).group(1)  # noqa: E731
    cell_w, cell_h, cell_x, cell_y = map(int, prop("FONTBOUNDINGBOX").split())
    ascent, descent = int(prop("FONT_ASCENT")), int(prop("FONT_DESCENT"))
    if ascent + descent != cell_h or cell_y != -descent or cell_x != 0:
        raise SystemExit(f"{path.name}: cell {cell_w}x{cell_h}{cell_x:+d}{cell_y:+d} "
                         f"is not ascent {ascent} + descent {descent}")
    glyphs = {}
    for m in re.finditer(r"^STARTCHAR .*?\nENCODING (-?\d+)\n(.*?)^BITMAP\n(.*?)^ENDCHAR",
                         text, re.M | re.S):
        code, head, bitmap = int(m.group(1)), m.group(2), m.group(3).split()
        w, h, xo, yo = map(int, re.search(r"^BBX (.+)$", head, re.M).group(1).split())
        dwidth = int(re.search(r"^DWIDTH (\d+) ", head, re.M).group(1))
        if dwidth != cell_w:
            raise SystemExit(f"{path.name}: U+{code:04X} advances {dwidth}, not {cell_w}")
        if len(bitmap) != h:
            raise SystemExit(f"{path.name}: U+{code:04X} has {len(bitmap)} rows, BBX says {h}")
        cell = [[0] * cell_w for _ in range(cell_h)]
        top = ascent - (yo + h)                     # the bitmap's first row in the cell
        for r, hexrow in enumerate(bitmap):
            bits = int(hexrow, 16)
            nbits = 4 * len(hexrow)
            for col in range(w):
                if bits >> (nbits - 1 - col) & 1:
                    y, x = top + r, xo + col
                    if not (0 <= y < cell_h and 0 <= x < cell_w):
                        raise SystemExit(f"{path.name}: U+{code:04X} paints outside its cell")
                    cell[y][x] = 1
        glyphs[code] = cell
    notice = re.search(r"^COMMENT\s+\*\s+(Copyright .+)$", text, re.M).group(1).strip()
    return {"w": cell_w, "h": cell_h, "ascent": ascent, "descent": descent,
            "version": prop("FONT_VERSION").strip('"'), "notice": notice, "glyphs": glyphs}


def spleen_face(path):
    """What the header holds: the box (the rows and columns any glyph taken
    paints), its glyphs' rows as bytes, and the metrics fm1_tft.h declares."""
    font = parse_bdf(path)
    missing = [c for c in range(FIRST, LAST + 1) if c not in font["glyphs"]]
    if missing:
        raise SystemExit(f"{path.name}: no glyph for {''.join(map(chr, missing))!r}")
    taken = {c: font["glyphs"][c] for c in range(FIRST, LAST + 1)}
    ink = [(y, x) for cell in taken.values() for y, row in enumerate(cell)
           for x, v in enumerate(row) if v]
    top, bottom = min(y for y, _ in ink), max(y for y, _ in ink)
    left, right = min(x for _, x in ink), max(x for _, x in ink)
    if left != 0:
        raise SystemExit(f"{path.name}: no glyph paints column 0; fm1_tft.c assumes one does")
    rows = bottom - top + 1
    cols = font["w"]
    if cols > 8:
        raise SystemExit(f"{path.name}: {cols} columns do not fit the tables' one byte a row")
    data = {c: [sum(1 << (cols - 1 - x) for x, v in enumerate(cell[y]) if v)
                for y in range(top, bottom + 1)] for c, cell in taken.items()}
    cap = [y for y, row in enumerate(taken[ord("H")]) if any(row)]
    baseline = font["ascent"] - top                 # rows of the box above the baseline
    if max(cap) + 1 != font["ascent"]:
        raise SystemExit(f"{path.name}: 'H' does not sit on the baseline")
    return {
        "cell": (font["w"], font["h"]), "version": font["version"], "notice": font["notice"],
        "top": top, "rows": rows, "cols": cols, "advance": font["w"], "ink_w": right + 1,
        "cap_h": max(cap) - min(cap) + 1, "baseline": baseline, "data": data,
        "bytes": (LAST - FIRST + 1) * rows,
    }


def render_spleen(prefix, array, path, header, face):
    w, h = face["cell"]
    dropped = [r for r in range(h) if not face["top"] <= r < face["top"] + face["rows"]]
    cell = (f"the BDF's {w} x {h} cell less row{'s' if len(dropped) > 1 else ''} "
            f"{' and '.join(map(str, dropped))}, which no character here paints" if dropped else
            f"the BDF's whole {w} x {h} cell, since some character paints each row")
    guard = header.name.upper().replace(".", "_") + "_"
    out = [
        f"/* {header.name} -- generated by sim/web/tools/gen_font.py from",
        f" * sim/web/third_party/spleen/{path.name}; do not edit.",
        " *",
        f" * Spleen {face['version']} {w}x{h}: {face['notice']}, under the",
        " * BSD 2-Clause licence (third_party/spleen/LICENSE): a binary built from this",
        " * table must carry that notice in its documentation (UPSTREAM.md there).",
        " *",
        f" * Printable ASCII (0x20-0x7E) in {face['cols']} x {face['rows']} cells:",
        f" * {cell}.",
        f" * One byte a row, bit {face['cols'] - 1} the leftmost column; rows 0-{face['baseline'] - 1} are above",
        f" * the baseline, and capitals {face['cap_h']} rows tall. {face['bytes']:,} bytes of flash. */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include <stdint.h>",
        "",
        f"#define FM1_FONT_{prefix}_FIRST 0x{FIRST:02X}",
        f"#define FM1_FONT_{prefix}_LAST 0x{LAST:02X}",
        f"#define FM1_FONT_{prefix}_COLS {face['cols']}",
        f"#define FM1_FONT_{prefix}_ROWS {face['rows']}",
        f"#define FM1_FONT_{prefix}_ADVANCE {face['advance']}",
        f"#define FM1_FONT_{prefix}_INK_W {face['ink_w']}",
        f"#define FM1_FONT_{prefix}_CAP_H {face['cap_h']}",
        f"#define FM1_FONT_{prefix}_BASELINE {face['baseline']}",
        "",
        f"static const uint8_t {array}[{LAST - FIRST + 1}][{face['rows']}] = {{",
    ]
    for c in range(FIRST, LAST + 1):
        rows = ", ".join(f"0x{r:02X}" for r in face["data"][c])
        out.append(f"  {{ {rows} }},  /* {label(c)} */")
    out += ["};", "", f"#endif /* {guard} */", ""]
    return "\n".join(out)


def outputs():
    yield OUT, render(parse(SRC.read_text()))
    for prefix, array, path, header in SPLEEN_FACES:
        yield header, render_spleen(prefix, array, path, header, spleen_face(path))


def main(argv):
    if "--sizes" in argv:
        sizes = {"MAIN": (LAST - FIRST + 1) * ROWS}
        sizes.update({p: spleen_face(path)["bytes"] for p, _, path, _ in SPLEEN_FACES})
        print(json.dumps(sizes))
        return 0
    stale = 0
    for path, text in outputs():
        if "--check" in argv:
            if not path.exists() or path.read_text() != text:
                print(f"{path} is out of date; run {Path(__file__).name}", file=sys.stderr)
                stale = 1
        else:
            path.write_text(text)
    return stale


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
