/* fm1_resampler.h -- sample-rate conversion from an engine's own rate down to
 * the host's (engines/resampler.md).
 *
 * An engine whose time constants are fixed in samples at its own rate (Braids
 * at 96 kHz, Plaits at 47,872.34 Hz) runs at that rate and hands its mix to
 * one of these, which delivers it at the host's rate (44,118 Hz on the FM-1).
 * Any real ratio from 1 to 4 (input rate at or above the output rate, up to
 * four times it); equal rates pass samples through bit for bit.
 *
 * Design: two stages, all coefficients const (flash on the FM-1).
 *   1. A polyphase windowed-sinc interpolator from the input rate to twice
 *      the output rate. Its kernel (sinc x Kaiser, beta 11, 12 intermediate
 *      samples wide, cut off at 0.96 of the output rate) is tabulated at 128
 *      phases per intermediate sample and linearly interpolated between
 *      phases, so any ratio works from one table. It keeps 0..0.408 fs_out
 *      flat and stops what would fold into the output's band at the
 *      intermediate rate (1.5 fs_out and up); what its wide transition lets
 *      through lands where stage 2 stops it. About 12 / rho taps per
 *      intermediate sample (rho = 2 fs_out / fs_in): 13 for Braids.
 *   2. A 123-tap linear-phase low-pass FIR (Kaiser, beta 9.3) decimating by
 *      two: flat to 0.408 fs_out, stopband from fs_out / 2 (the output's
 *      Nyquist). 62 multiplies, on pre-added symmetric pairs.
 * Per output sample at 96,000 -> 44,118 Hz: about 26 kernel taps (two
 * multiply-adds each) and the low-pass's 62 multiplies, ~114 in all.
 * Measured (engines/resampler.md): flat within 0.005 dB to 0.408 fs_out
 * (18 kHz at 44,118 Hz); everything that would land anywhere in
 * 0..fs_out / 2 from content above the output's Nyquist, and every image
 * and spur, at least 93 dB down; linear phase, group delay 30 output
 * samples (0.680 ms at 44,118 Hz).
 *
 * Use (one instance per mono stream; state is the struct, no heap):
 *
 *   fm1_resampler_t rs;
 *   if (!fm1_resampler_init(&rs, 96000.0f, host_rate)) refuse the host;
 *   for each output sample:
 *     while ((need = fm1_resampler_needed(&rs)) > 0)
 *       fm1_resampler_push(&rs, next_input, need);   (or fewer at a time)
 *     out = fm1_resampler_pop(&rs);
 *
 * Inputs are pulled only as each output needs them, so an engine that renders
 * its own fixed blocks on demand produces the same output whatever block size
 * the host asks for. fm1_resampler_process does the same over arrays.
 * Initialise every instance before use: init writes every field.
 *
 * Plain C99 (also valid C++11), static inline, no allocation, no libm calls.
 * MIT licence, like the rest of this repository.
 */
#ifndef FM1_RESAMPLER_H_
#define FM1_RESAMPLER_H_

#include <stdint.h>

#define FM1_RESAMPLER_SPAN 12          /* stage-1 kernel width, intermediate samples */
#define FM1_RESAMPLER_PHASES 128       /* kernel table entries per intermediate sample */
#define FM1_RESAMPLER_KERNEL_LEN (FM1_RESAMPLER_SPAN / 2 * FM1_RESAMPLER_PHASES + 1)
#define FM1_RESAMPLER_DELAY 30         /* group delay, output samples */
#define FM1_RESAMPLER_LP_LEN (4 * FM1_RESAMPLER_DELAY + 3)    /* stage-2 taps: 123 */
#define FM1_RESAMPLER_LP_PAIRS (2 * FM1_RESAMPLER_DELAY + 1)  /* its symmetric pairs: 61 */
#define FM1_RESAMPLER_MAX_RATIO 4      /* input rate / output rate */
/* One output reads at most 27 consecutive inputs, at the 4:1 limit
 * (fm1-resampler-test window); the input ring keeps 32, so the slot the next
 * push fills is never read. */
#define FM1_RESAMPLER_IN_CAP 32
#define FM1_RESAMPLER_MID_CAP FM1_RESAMPLER_LP_LEN   /* intermediate samples kept */

#define FM1_RESAMPLER_OFF 0u           /* refused by init: takes and gives nothing */
#define FM1_RESAMPLER_PASS 1u          /* equal rates: samples pass bit for bit */
#define FM1_RESAMPLER_CONVERT 2u

/* The stage-1 kernel, one half: c sinc(c u) x Kaiser(u, beta 11), c = 0.96,
 * for u = 0 .. 6 intermediate samples in steps of 1/128 (a low-pass at 0.96 of
 * the intermediate rate's Nyquist, integral 1). Generated by
 * `python -m tests.test_engines_resampler`. */
static const float fm1_resampler_kernel[FM1_RESAMPLER_KERNEL_LEN] = {
  0.959999979f, 0.959902644f, 0.959610581f, 0.959124029f, 0.958443046f, 0.957568049f,
  0.956499279f, 0.95523721f, 0.95378232f, 0.952135324f, 0.9502967f, 0.948267341f,
  0.946048021f, 0.943639636f, 0.941043198f, 0.938259661f, 0.935290217f, 0.932135999f,
  0.928798378f, 0.925278664f, 0.921578228f, 0.917698622f, 0.913641393f, 0.909408092f,
  0.905000508f, 0.900420368f, 0.89566952f, 0.890749872f, 0.88566339f, 0.880412102f,
  0.874998093f, 0.869423449f, 0.863690555f, 0.857801497f, 0.851758778f, 0.845564663f,
  0.839221656f, 0.83273232f, 0.826099098f, 0.819324672f, 0.812411666f, 0.805362821f,
  0.798180938f, 0.7908687f, 0.783429086f, 0.775864899f, 0.768179119f, 0.760374784f,
  0.752454817f, 0.744422257f, 0.736280322f, 0.728032053f, 0.719680607f, 0.711229205f,
  0.702681065f, 0.694039404f, 0.685307622f, 0.676488876f, 0.667586505f, 0.658603966f,
  0.649544537f, 0.640411675f, 0.631208718f, 0.621939123f, 0.612606287f, 0.603213668f,
  0.593764782f, 0.584263027f, 0.574711859f, 0.565114856f, 0.555475354f, 0.545796931f,
  0.536083043f, 0.526337206f, 0.51656276f, 0.506763339f, 0.496942341f, 0.487103224f,
  0.477249414f, 0.467384338f, 0.457511485f, 0.44763419f, 0.437755883f, 0.4278799f,
  0.418009639f, 0.408148408f, 0.398299515f, 0.388466239f, 0.378651857f, 0.368859619f,
  0.359092683f, 0.349354267f, 0.339647472f, 0.329975456f, 0.320341289f, 0.310747981f,
  0.301198572f, 0.291696012f, 0.282243252f, 0.272843182f, 0.263498604f, 0.254212379f,
  0.244987234f, 0.235825911f, 0.226731077f, 0.217705354f, 0.208751321f, 0.199871495f,
  0.191068366f, 0.182344362f, 0.173701867f, 0.165143192f, 0.156670615f, 0.148286343f,
  0.139992535f, 0.131791323f, 0.123684734f, 0.115674764f, 0.107763357f, 0.0999523848f,
  0.0922436714f, 0.0846389681f, 0.0771399736f, 0.069748342f, 0.0624656379f, 0.0552933849f,
  0.0482330434f, 0.0412860066f, 0.0344536081f, 0.027737122f, 0.0211377554f, 0.0146566564f,
  0.00829491019f, 0.00205353927f, -0.00406649709f, -0.0100643011f, -0.0159390401f, -0.0216899402f,
  -0.0273162946f, -0.0328174531f, -0.0381928347f, -0.0434419177f, -0.0485642366f, -0.0535593964f,
  -0.0584270544f, -0.0631669387f, -0.0677788332f, -0.0722625852f, -0.0766180903f, -0.0808453187f,
  -0.0849442855f, -0.0889150798f, -0.092757836f, -0.0964727551f, -0.100060083f, -0.10352014f,
  -0.106853276f, -0.110059924f, -0.113140553f, -0.116095692f, -0.118925914f, -0.121631861f,
  -0.124214217f, -0.126673698f, -0.129011109f, -0.131227285f, -0.133323073f, -0.135299444f,
  -0.137157336f, -0.138897777f, -0.140521839f, -0.142030612f, -0.143425256f, -0.144706964f,
  -0.145876944f, -0.146936491f, -0.147886887f, -0.148729488f, -0.149465665f, -0.150096849f,
  -0.150624469f, -0.151050001f, -0.151374996f, -0.151600957f, -0.151729465f, -0.151762128f,
  -0.151700571f, -0.151546448f, -0.151301444f, -0.15096724f, -0.150545582f, -0.150038198f,
  -0.149446875f, -0.148773387f, -0.148019522f, -0.147187129f, -0.146278024f, -0.145294055f,
  -0.144237086f, -0.143109009f, -0.141911685f, -0.140647024f, -0.139316916f, -0.1379233f,
  -0.136468068f, -0.134953141f, -0.133380473f, -0.131751969f, -0.130069569f, -0.128335208f,
  -0.126550823f, -0.124718331f, -0.122839674f, -0.120916776f, -0.118951552f, -0.11694593f,
  -0.114901803f, -0.112821087f, -0.110705674f, -0.10855744f, -0.106378272f, -0.104170017f,
  -0.101934537f, -0.0996736735f, -0.0973892361f, -0.095083043f, -0.0927568898f, -0.0904125497f,
  -0.0880517811f, -0.0856763348f, -0.0832879245f, -0.0808882564f, -0.0784790143f, -0.0760618597f,
  -0.0736384392f, -0.0712103695f, -0.068779245f, -0.0663466305f, -0.0639140904f, -0.0614831336f,
  -0.059055265f, -0.0566319562f, -0.0542146526f, -0.0518047735f, -0.0494037122f, -0.0470128283f,
  -0.044633463f, -0.0422669202f, -0.0399144776f, -0.0375773907f, -0.0352568738f, -0.0329541154f,
  -0.0306702778f, -0.0284064878f, -0.0261638444f, -0.0239434149f, -0.021746235f, -0.0195733085f,
  -0.0174256098f, -0.0153040774f, -0.0132096233f, -0.0111431228f, -0.00910542347f, -0.00709733739f,
  -0.00511964643f, -0.00317310006f, -0.00125841552f, 0.000623721746f, 0.00247265864f, 0.00428777374f,
  0.00606847741f, 0.00781421177f, 0.00952445064f, 0.0111986995f, 0.0128364954f, 0.0144374045f,
  0.0160010271f, 0.0175269898f, 0.0190149564f, 0.020464614f, 0.0218756832f, 0.0232479144f,
  0.0245810859f, 0.0258750059f, 0.0271295123f, 0.028344471f, 0.0295197722f, 0.0306553412f,
  0.0317511223f, 0.0328070968f, 0.0338232592f, 0.0347996429f, 0.0357363038f, 0.0366333127f,
  0.0374907814f, 0.0383088365f, 0.0390876271f, 0.0398273319f, 0.0405281484f, 0.0411902964f,
  0.0418140218f, 0.0423995852f, 0.0429472774f, 0.0434573963f, 0.0439302735f, 0.0443662554f,
  0.0447656997f, 0.04512899f, 0.0454565287f, 0.0457487293f, 0.0460060276f, 0.0462288707f,
  0.0464177281f, 0.0465730727f, 0.0466954038f, 0.046785228f, 0.0468430668f, 0.046869453f,
  0.0468649343f, 0.0468300655f, 0.0467654169f, 0.0466715656f, 0.0465491042f, 0.0463986211f,
  0.046220731f, 0.0460160486f, 0.0457851924f, 0.0455287918f, 0.0452474803f, 0.0449419059f,
  0.0446127094f, 0.0442605466f, 0.0438860729f, 0.0434899442f, 0.0430728272f, 0.0426353887f,
  0.0421782918f, 0.0417022109f, 0.0412078165f, 0.040695779f, 0.0401667729f, 0.0396214649f,
  0.039060533f, 0.0384846404f, 0.0378944613f, 0.0372906588f, 0.036673896f, 0.036044836f,
  0.0354041383f, 0.0347524546f, 0.034090437f, 0.0334187299f, 0.0327379704f, 0.0320487991f,
  0.031351842f, 0.0306477249f, 0.0299370643f, 0.029220473f, 0.0284985527f, 0.0277719013f,
  0.0270411056f, 0.0263067503f, 0.0255694054f, 0.0248296373f, 0.0240880027f, 0.0233450457f,
  0.0226013064f, 0.0218573138f, 0.0211135857f, 0.0203706324f, 0.0196289513f, 0.0188890323f,
  0.018151354f, 0.0174163859f, 0.0166845825f, 0.0159563944f, 0.0152322529f, 0.0145125855f,
  0.0137978047f, 0.0130883139f, 0.0123845013f, 0.0116867488f, 0.0109954234f, 0.0103108808f,
  0.0096334666f, 0.00896351226f, 0.00830134004f, 0.00764726009f, 0.00700156856f, 0.0063645523f,
  0.00573648559f, 0.00511763059f, 0.00450823782f, 0.00390854664f, 0.00331878476f, 0.00273916754f,
  0.00216989918f, 0.00161117269f, 0.00106316921f, 0.000526058779f, 8.11572624e-18f, -0.000514859566f,
  -0.00101838342f, -0.00151044619f, -0.0019909332f, -0.0024597405f, -0.00291677495f, -0.00336195389f,
  -0.00379520468f, -0.00421646517f, -0.00462568365f, -0.00502281729f, -0.00540783396f, -0.0057807113f,
  -0.00614143489f, -0.00649000145f, -0.00682641566f, -0.00715069147f, -0.00746285124f, -0.00776292663f,
  -0.00805095676f, -0.00832698867f, -0.00859107915f, -0.00884329155f, -0.00908369664f, -0.00931237265f,
  -0.00952940527f, -0.00973488763f, -0.00992891844f, -0.010111603f, -0.0102830548f, -0.0104433913f,
  -0.0105927363f, -0.0107312212f, -0.0108589809f, -0.0109761562f, -0.0110828932f, -0.0111793419f,
  -0.0112656569f, -0.0113420002f, -0.0114085339f, -0.0114654275f, -0.0115128513f, -0.0115509806f,
  -0.011579996f, -0.0116000781f, -0.0116114113f, -0.0116141839f, -0.0116085857f, -0.0115948096f,
  -0.0115730502f, -0.011543504f, -0.0115063703f, -0.0114618465f, -0.0114101367f, -0.011351442f,
  -0.0112859663f, -0.0112139136f, -0.0111354897f, -0.0110508986f, -0.010960348f, -0.0108640417f,
  -0.0107621867f, -0.0106549887f, -0.0105426526f, -0.0104253832f, -0.0103033846f, -0.0101768598f,
  -0.0100460108f, -0.00991103984f, -0.00977214519f, -0.00962952711f, -0.00948338117f, -0.00933390297f,
  -0.00918128714f, -0.00902572367f, -0.00886740349f, -0.00870651379f, -0.00854323991f, -0.00837776437f,
  -0.00821026787f, -0.00804093014f, -0.00786992442f, -0.00769742439f, -0.00752360001f, -0.00734861847f,
  -0.00717264414f, -0.00699583767f, -0.00681835786f, -0.00664035883f, -0.00646199333f, -0.00628340896f,
  -0.00610475196f, -0.0059261634f, -0.00574778253f, -0.00556974346f, -0.00539217889f, -0.00521521643f,
  -0.00503898039f, -0.00486359233f, -0.00468916912f, -0.00451582531f, -0.00434367079f, -0.00417281268f,
  -0.00400335342f, -0.00383539242f, -0.00366902584f, -0.00350434589f, -0.00334144058f, -0.00318039535f,
  -0.00302129122f, -0.00286420598f, -0.00270921388f, -0.00255638547f, -0.00240578759f, -0.00225748401f,
  -0.00211153459f, -0.00196799613f, -0.00182692194f, -0.00168836163f, -0.00155236165f, -0.00141896529f,
  -0.00128821237f, -0.00116013957f, -0.00103478029f, -0.000912164978f, -0.000792320876f, -0.000675272138f,
  -0.000561040011f, -0.00044964283f, -0.000341095962f, -0.000235412066f, -0.000132600908f, -3.26696136e-05f,
  6.43773456e-05f, 0.000158538081f, 0.000249813282f, 0.000338206039f, 0.000423721882f, 0.000506368699f,
  0.000586156617f, 0.000663098006f, 0.000737207301f, 0.000808501209f, 0.000876998238f, 0.000942718936f,
  0.00100568577f, 0.0010659229f, 0.00112345652f, 0.00117831409f, 0.00123052497f, 0.00128011999f,
  0.00132713153f, 0.00137159333f, 0.00141354033f, 0.00145300908f, 0.00149003696f, 0.00152466295f,
  0.00155692664f, 0.00158686901f, 0.00161453185f, 0.00163995777f, 0.00166319043f, 0.00168427418f,
  0.00170325395f, 0.00172017538f, 0.00173508492f, 0.00174802926f, 0.00175905565f, 0.00176821195f,
  0.00177554612f, 0.00178110658f, 0.001784942f, 0.00178710127f, 0.0017876334f, 0.00178658741f,
  0.00178401265f, 0.00177995826f, 0.00177447335f, 0.00176760706f, 0.00175940816f, 0.00174992566f,
  0.00173920812f, 0.00172730361f, 0.00171426032f, 0.00170012598f, 0.00168494787f, 0.00166877301f,
  0.00165164762f, 0.00163361803f, 0.00161472964f, 0.0015950274f, 0.00157455588f, 0.00155335886f,
  0.00153147953f, 0.0015089605f, 0.00148584379f, 0.00146217062f, 0.0014379815f, 0.00141331635f,
  0.00138821406f, 0.00136271329f, 0.00133685116f, 0.00131066481f, 0.00128418999f, 0.00125746173f,
  0.00123051449f, 0.00120338169f, 0.00117609592f, 0.00114868884f, 0.00112119142f, 0.00109363371f,
  0.00106604456f, 0.00103845249f, 0.00101088476f, 0.000983367907f, 0.000955927302f, 0.000928587862f,
  0.000901373278f, 0.000874306483f, 0.000847409538f, 0.00082070363f, 0.000794208958f, 0.000767944963f,
  0.000741930271f, 0.000716182461f, 0.000690718472f, 0.000665554195f, 0.000640704879f, 0.000616184843f,
  0.000592007593f, 0.000568185817f, 0.000544731505f, 0.000521655777f, 0.000498968991f, 0.000476680812f,
  0.000454800029f, 0.000433334819f, 0.000412292633f, 0.000391680165f, 0.00037150344f, 0.000351767812f,
  0.000332478026f, 0.000313638069f, 0.000295251433f, 0.000277320913f, 0.000259848719f, 0.000242836497f,
  0.000226285338f, 0.000210195794f, 0.000194567838f, 0.000179400988f, 0.000164694226f, 0.000150446096f,
  0.000136654649f, 0.000123317484f, 0.000110431822f, 9.79944234e-05f, 8.60016735e-05f, 7.44495919e-05f,
  6.33338204e-05f, 5.26496697e-05f, 4.23921229e-05f, 3.25558503e-05f, 2.31352351e-05f, 1.41243736e-05f,
  5.517109e-06f, -2.69296311e-06f, -1.05124764e-05f, -1.79482795e-05f, -2.50074208e-05f, -3.16971309e-05f,
  -3.80248093e-05f, -4.39980104e-05f, -4.9624432e-05f, -5.49118995e-05f, -5.98683437e-05f, -6.45018008e-05f,
  -6.88204018e-05f, -7.28323284e-05f, -7.65458462e-05f, -7.99692643e-05f, -8.3110921e-05f, -8.59791908e-05f,
  -8.85824629e-05f, -9.0929112e-05f, -9.30275419e-05f, -9.48860979e-05f, -9.6513133e-05f, -9.7916949e-05f,
  -9.91058041e-05f, -0.000100087906f, -0.000100871395f, -0.000101464342f, -0.00010187475f, -0.000102110527f,
  -0.000102179489f, -0.000102089361f, -0.000101847749f, -0.000101462159f, -0.000100939978f, -0.000100288467f,
  -9.95147639e-05f, -9.86258747e-05f, -9.76286683e-05f, -9.6529875e-05f, -9.53360723e-05f, -9.40536993e-05f,
  -9.26890425e-05f, -9.12482355e-05f, -8.97372593e-05f, -8.81619271e-05f, -8.65279071e-05f, -8.48406853e-05f,
  -8.31056022e-05f, -8.13278384e-05f, -7.95123851e-05f, -7.76640882e-05f, -7.5787626e-05f, -7.38875096e-05f,
  -7.19680756e-05f, -7.00335004e-05f, -6.80878002e-05f, -6.6134824e-05f, -6.41782535e-05f, -6.22216103e-05f,
  -6.02682558e-05f, -5.8321395e-05f, -5.63840731e-05f, -5.44591712e-05f, -5.25494288e-05f, -5.06574288e-05f,
  -4.87856014e-05f, -4.69362349e-05f, -4.51114684e-05f, -4.33132991e-05f, -4.15435934e-05f, -3.98040684e-05f,
  -3.80963138e-05f, -3.64217958e-05f, -3.47818386e-05f, -3.31776573e-05f, -3.1610336e-05f, -3.00808424e-05f,
  -2.85900351e-05f, -2.71386598e-05f, -2.57273514e-05f, -2.43566465e-05f, -2.30269779e-05f, -2.17386823e-05f,
  -2.04920034e-05f, -1.92870957e-05f, -1.81240284e-05f, -1.7002787e-05f, -1.59232786e-05f, -1.4885336e-05f,
  -1.38887181e-05f, -1.29331174e-05f, -1.20181612e-05f, -1.11434165e-05f, -1.03083912e-05f, -9.51253969e-06f,
  -8.75526439e-06f, -8.03592138e-06f, -7.35382173e-06f, -6.70823511e-06f, -6.09839299e-06f, -5.52349275e-06f,
  -4.98269947e-06f,
};

/* Stage 2's taps, outermost first: 2 f sinc(2 f m) x Kaiser(m, beta 9.3) at
 * the offsets m = 61 .. 1 from the centre tap, then the centre tap, with
 * f = 0.2261 cycles per intermediate sample (19,950 Hz at 44,118 Hz);
 * scaled so that the centre and twice the sides sum to 1 (unity at DC). */
static const float fm1_resampler_lowpass[FM1_RESAMPLER_LP_PAIRS + 1] = {
  -6.3196544e-06f, -4.30278396e-06f, 1.36683657e-05f, 1.53014007e-05f,
  -2.10547169e-05f, -3.7323447e-05f, 2.29130455e-05f, 7.30346146e-05f,
  -1.01068053e-05f, -0.000121586738f, -2.94556667e-05f, 0.00017604827f,
  0.000108751083f, -0.000221180046f, -0.000237955304f, 0.00023242821f,
  0.000419380696f, -0.00017705519f, -0.000641766877f, 1.81442174e-05f,
  0.000875134312f, 0.00027823032f, -0.00106774666f, -0.000733044697f,
  0.00114679604f, 0.00134274771f, -0.00102413201f, -0.00206798594f,
  0.000607678725f, 0.00282508484f, 0.000181814234f, -0.00348286494f,
  -0.0013901965f, 0.00386698195f, 0.0030081179f, -0.0037730278f,
  -0.00495134806f, 0.00298823835f, 0.0070466944f, -0.00132000155f,
  -0.00902632624f, -0.00137224456f, 0.0105316248f, 0.00514634559f,
  -0.0111249033f, -0.00995317195f, 0.0103028519f, 0.015623603f,
  -0.0074980068f, -0.0218703561f, 0.00203824323f, 0.028306203f,
  0.00701021357f, -0.0344776325f, -0.0213465244f, 0.0399104394f,
  0.0452316776f, -0.0441615507f, -0.0945397168f, 0.0468700528f,
  0.3143695f, 0.452201903f,
};

typedef struct fm1_resampler {
  int64_t step;       /* input samples per intermediate sample, 32.32 fixed point */
  int64_t lead;       /* step + the kernel's reach + 1: input an output needs past rel */
  int64_t rel;        /* next intermediate sample's input position less the inputs
                         received so far, 32.32 (at or below zero once fed) */
  uint32_t tap_step;  /* kernel table entries per input sample, 16.16 */
  float gain;         /* intermediate samples per input sample (rho) */
  uint32_t mode;      /* FM1_RESAMPLER_OFF, _PASS or _CONVERT */
  uint32_t held;      /* pass-through: in[0] holds a sample not yet popped */
  uint32_t in_w, mid_w;   /* next write slot of each ring */
  /* Rings, each written twice (at w and w + CAP) so any window of CAP
   * consecutive samples is contiguous. */
  float in[2 * FM1_RESAMPLER_IN_CAP];
  float mid[2 * FM1_RESAMPLER_MID_CAP];   /* the last 123 intermediate samples */
} fm1_resampler_t;

/* Sets r up to convert in_rate to out_rate. Returns 1, or 0 (r then passes
 * nothing: needed() is 0 and pop() returns 0) when the ratio
 * in_rate / out_rate is outside 1..FM1_RESAMPLER_MAX_RATIO or either rate is
 * not a positive finite number. */
static inline int fm1_resampler_init(fm1_resampler_t *r, float in_rate, float out_rate) {
  uint32_t i;
  double ratio, rho;
  r->step = r->lead = r->rel = 0;
  r->tap_step = 0;
  r->gain = 0.0f;
  r->mode = FM1_RESAMPLER_OFF;
  r->held = 0;
  r->in_w = r->mid_w = 0;
  for (i = 0; i < 2 * FM1_RESAMPLER_IN_CAP; ++i) r->in[i] = 0.0f;
  for (i = 0; i < 2 * FM1_RESAMPLER_MID_CAP; ++i) r->mid[i] = 0.0f;
  if (!(in_rate > 0.0f && out_rate > 0.0f && in_rate < 1e30f && out_rate < 1e30f)) return 0;
  ratio = (double)in_rate / (double)out_rate;
  if (in_rate == out_rate) {
    r->mode = FM1_RESAMPLER_PASS;
    return 1;
  }
  if (!(ratio >= 1.0 && ratio <= FM1_RESAMPLER_MAX_RATIO)) return 0;
  rho = 2.0 / ratio;                 /* in [0.5, 2] */
  r->mode = FM1_RESAMPLER_CONVERT;
  r->gain = (float)rho;
  r->step = (int64_t)(ratio / 2.0 * 4294967296.0 + 0.5);
  r->tap_step = (uint32_t)(rho * FM1_RESAMPLER_PHASES * 65536.0 + 0.5);
  /* The kernel reaches SPAN / 2 intermediate samples, SPAN / (2 rho) input
   * samples, either side; one input more covers the rounding of tap_step. */
  r->lead = r->step + (int64_t)(FM1_RESAMPLER_SPAN / (2.0 * rho) * 4294967296.0 + 0.5) +
            ((int64_t)1 << 32);
  return 1;
}

/* Input samples r must receive before the next fm1_resampler_pop. */
static inline uint32_t fm1_resampler_needed(const fm1_resampler_t *r) {
  int64_t v;
  if (r->mode != FM1_RESAMPLER_CONVERT) return r->mode == FM1_RESAMPLER_PASS && !r->held;
  v = r->rel + r->lead;
  return v > 0 ? (uint32_t)(((uint64_t)v + 0xFFFFFFFFu) >> 32) : 0u;
}

/* Takes up to n samples, never more than fm1_resampler_needed(r); returns
 * how many it took. */
static inline uint32_t fm1_resampler_push(fm1_resampler_t *r, const float *in, uint32_t n) {
  uint32_t i, need = fm1_resampler_needed(r);
  if (n > need) n = need;
  if (r->mode != FM1_RESAMPLER_CONVERT) {
    if (n) { r->in[0] = in[0]; r->held = 1; }
    return n;
  }
  for (i = 0; i < n; ++i) {
    r->in[r->in_w] = r->in[r->in_w + FM1_RESAMPLER_IN_CAP] = in[i];
    if (++r->in_w == FM1_RESAMPLER_IN_CAP) r->in_w = 0;
  }
  r->rel -= (int64_t)n << 32;
  return n;
}

/* The kernel at table position t (16.16), linearly interpolated. */
static inline float fm1_resampler_tap_(uint32_t t) {
  const float *k = &fm1_resampler_kernel[t >> 16];
  return k[0] + (float)(t & 0xFFFFu) * (1.0f / 65536.0f) * (k[1] - k[0]);
}

/* One intermediate sample at input position rel (relative to the inputs
 * received): the sum of x[n] k((P - n) rho) over the inputs the kernel
 * reaches. The taps at or before P walk the half table outwards one way,
 * the later ones the other; two sums, so the two chains overlap. */
static inline float fm1_resampler_intermediate_(fm1_resampler_t *r) {
  const uint32_t ts = r->tap_step;
  const uint32_t end = (uint32_t)(FM1_RESAMPLER_KERNEL_LEN - 1) << 16;
  const int64_t rel = r->rel;
  const uint32_t frac = (uint32_t)((uint64_t)rel & 0xFFFFFFFFu);
  /* The input at floor(P): the newest input is at in_w - 1 + CAP. */
  const float *before = &r->in[r->in_w + FM1_RESAMPLER_IN_CAP - 1] + (rel >> 32) + 1;
  const float *after = before + 1;
  uint32_t tb = (uint32_t)(((uint64_t)frac * ts) >> 32);
  uint32_t ta = (uint32_t)((((uint64_t)1 << 32) - frac) * ts >> 32);
  float sb = 0.0f, sa = 0.0f;
  for (; tb < end && ta < end; tb += ts, ta += ts, --before, ++after) {
    sb += fm1_resampler_tap_(tb) * *before;
    sa += fm1_resampler_tap_(ta) * *after;
  }
  for (; tb < end; tb += ts, --before) sb += fm1_resampler_tap_(tb) * *before;
  for (; ta < end; ta += ts, ++after) sa += fm1_resampler_tap_(ta) * *after;
  r->rel = rel + r->step;
  return (sb + sa) * r->gain;
}

/* The next output sample. Returns 0 and changes nothing if r still needs
 * input (fm1_resampler_needed > 0). */
static inline float fm1_resampler_pop(fm1_resampler_t *r) {
  const float *h = fm1_resampler_lowpass, *e;
  float y0 = 0.0f, y1 = 0.0f, y2 = 0.0f, y3 = 0.0f;
  uint32_t j;
  if (r->mode != FM1_RESAMPLER_CONVERT) {
    if (!r->held) return 0.0f;
    r->held = 0;
    return r->in[0];
  }
  if (fm1_resampler_needed(r)) return 0.0f;
  for (j = 0; j < 2; ++j) {             /* intermediate samples 2k and 2k + 1 */
    const float x = fm1_resampler_intermediate_(r);
    r->mid[r->mid_w] = r->mid[r->mid_w + FM1_RESAMPLER_MID_CAP] = x;
    if (++r->mid_w == FM1_RESAMPLER_MID_CAP) r->mid_w = 0;
  }
  /* Output k is the low-pass centred on intermediate sample 2k - 60, the
   * middle of the last 123 (2k - 121 .. 2k + 1, oldest at e[0]); the pairs
   * from the outside in, over four sums so their chains overlap. */
  e = &r->mid[r->mid_w];
  for (j = 0; j + 4 <= FM1_RESAMPLER_LP_PAIRS; j += 4) {
    y0 += h[j] * (e[j] + e[FM1_RESAMPLER_LP_LEN - 1 - j]);
    y1 += h[j + 1] * (e[j + 1] + e[FM1_RESAMPLER_LP_LEN - 2 - j]);
    y2 += h[j + 2] * (e[j + 2] + e[FM1_RESAMPLER_LP_LEN - 3 - j]);
    y3 += h[j + 3] * (e[j + 3] + e[FM1_RESAMPLER_LP_LEN - 4 - j]);
  }
  for (; j < FM1_RESAMPLER_LP_PAIRS; ++j) y0 += h[j] * (e[j] + e[FM1_RESAMPLER_LP_LEN - 1 - j]);
  return ((y0 + y1) + (y2 + y3)) + h[FM1_RESAMPLER_LP_PAIRS] * e[FM1_RESAMPLER_LP_PAIRS];
}

/* Array form: takes inputs from in[0..n_in) as outputs need them and writes
 * up to max_out outputs; returns how many it wrote, and stores how many
 * inputs it took in *n_used (when not NULL). Stops early when the input runs
 * out; what it took is kept for the next call. */
static inline uint32_t fm1_resampler_process(fm1_resampler_t *r, const float *in, uint32_t n_in,
                                             uint32_t *n_used, float *out, uint32_t max_out) {
  uint32_t used = 0, made = 0;
  while (made < max_out) {
    if (used < n_in) used += fm1_resampler_push(r, in + used, n_in - used);
    if (fm1_resampler_needed(r)) break;
    out[made++] = fm1_resampler_pop(r);
  }
  if (n_used) *n_used = used;
  return made;
}

/* Group delay in output samples: 0 for pass-through, else
 * FM1_RESAMPLER_DELAY = 30 (output k is the signal at input time
 * (k - 30) / out_rate; input 0 is time 0). */
static inline float fm1_resampler_delay(const fm1_resampler_t *r) {
  return r->mode == FM1_RESAMPLER_CONVERT ? (float)FM1_RESAMPLER_DELAY : 0.0f;
}

#endif /* FM1_RESAMPLER_H_ */
