/* fm1_resampler.h -- sample-rate conversion from an engine's own rate down to
 * the host's (engines/resampler.md).
 *
 * An engine whose time constants are fixed in samples at its own rate (Braids
 * at 96 kHz, Plaits at 47,872.34 Hz) runs at that rate and hands its mix to
 * one of these, which delivers it at the host's rate (44,118 Hz on the FM-1).
 * Any real ratio from 1 to 4 (input rate at or above the output rate, up to
 * four times it); equal rates pass samples through bit for bit.
 *
 * Design: two stages, all coefficients const (flash on the FM-1).
 *   1. A polyphase windowed-sinc interpolator from the input rate to twice
 *      the output rate. Its kernel (sinc x Kaiser, beta 11, 12 intermediate
 *      samples wide) is tabulated at 128 phases per intermediate sample and
 *      linearly interpolated between phases, so any ratio works from one
 *      table. It only has to keep 0..0.408 fs_out clean at the intermediate
 *      rate, so its transition band is wide (0.408 to 1.592 fs_out) and it
 *      needs about 12 / rho taps (rho = 2 fs_out / fs_in): 13 for Braids.
 *   2. A 67-tap half-band FIR (Kaiser, beta 9.5) decimating by two: 17
 *      multiplies, its other taps being zero or symmetric.
 * Per output sample at 96,000 -> 44,118 Hz: about 26 kernel taps (two
 * multiply-adds each) and 17 half-band multiplies, ~70 in all. Measured
 * (engines/resampler.md): flat within 0.001 dB to 0.408 fs_out (18 kHz at
 * 44,118 Hz); anything above the output's Nyquist that would land in
 * 0..0.408 fs_out is at least 90 dB down; content between fs_out / 2 and
 * 0.592 fs_out (22.06 to 26.1 kHz) folds into 0.408..0.5 fs_out (18 to
 * 22.06 kHz), attenuated by the half-band's transition band only; linear
 * phase, group delay 16 output samples (0.363 ms at 44,118 Hz).
 *
 * Use (one instance per mono stream; state is the struct, no heap):
 *
 *   fm1_resampler_t rs;
 *   if (!fm1_resampler_init(&rs, 96000.0f, host_rate)) refuse the host;
 *   for each output sample:
 *     while ((need = fm1_resampler_needed(&rs)) > 0)
 *       fm1_resampler_push(&rs, next_input, need);   (or fewer at a time)
 *     out = fm1_resampler_pop(&rs);
 *
 * Inputs are pulled only as each output needs them, so an engine that renders
 * its own fixed blocks on demand produces the same output whatever block size
 * the host asks for. fm1_resampler_process does the same over arrays.
 * Initialise every instance before use: init writes every field.
 *
 * Plain C99 (also valid C++11), static inline, no allocation, no libm calls
 * outside init. MIT licence, like the rest of this repository.
 */
#ifndef FM1_RESAMPLER_H_
#define FM1_RESAMPLER_H_

#include <stdint.h>

#define FM1_RESAMPLER_SPAN 12          /* stage-1 kernel width, intermediate samples */
#define FM1_RESAMPLER_PHASES 128       /* kernel table entries per intermediate sample */
#define FM1_RESAMPLER_KERNEL_LEN (FM1_RESAMPLER_SPAN / 2 * FM1_RESAMPLER_PHASES + 1)
#define FM1_RESAMPLER_HB_K 16          /* half-band of 4 K + 3 = 67 taps */
#define FM1_RESAMPLER_HB_PAIRS (FM1_RESAMPLER_HB_K + 1)
#define FM1_RESAMPLER_MAX_RATIO 4      /* input rate / output rate */
/* Ring sizes. The input ring holds what one output reads: at most
 * step + 2 x kernel reach + 3 = 29 samples at the maximum ratio. */
#define FM1_RESAMPLER_IN_CAP 32
#define FM1_RESAMPLER_SIDE_CAP (2 * FM1_RESAMPLER_HB_K + 2)
#define FM1_RESAMPLER_CENTRE_CAP (FM1_RESAMPLER_HB_K + 1)

#define FM1_RESAMPLER_OFF 0u           /* refused by init: takes and gives nothing */
#define FM1_RESAMPLER_PASS 1u          /* equal rates: samples pass bit for bit */
#define FM1_RESAMPLER_CONVERT 2u

/* The stage-1 kernel, one half: sinc(u) x Kaiser(u, beta 11) for
 * u = 0 .. 6 intermediate samples in steps of 1/128 (cut off at the
 * intermediate rate's Nyquist; exactly 1 at u = 0 and 0 at the other
 * integers). Generated by `python -m tests.test_engines_resampler`. */
static const float fm1_resampler_kernel[FM1_RESAMPLER_KERNEL_LEN] = {
  1.0f, 0.999890685f, 0.999562919f, 0.999016702f, 0.998252392f, 0.997270226f,
  0.996070683f, 0.994654298f, 0.993021667f, 0.991173446f, 0.989110529f, 0.986833751f,
  0.984344125f, 0.981642663f, 0.978730619f, 0.975609183f, 0.972279787f, 0.968743801f,
  0.965002716f, 0.961058259f, 0.956912041f, 0.952565908f, 0.94802165f, 0.943281233f,
  0.938346803f, 0.933220327f, 0.927904069f, 0.922400355f, 0.91671145f, 0.910839856f,
  0.904787958f, 0.898558497f, 0.892153978f, 0.885577202f, 0.878830969f, 0.871918023f,
  0.864841402f, 0.857604086f, 0.850209057f, 0.842659473f, 0.834958494f, 0.827109337f,
  0.819115341f, 0.810979724f, 0.802705944f, 0.794297516f, 0.78575778f, 0.777090371f,
  0.768298864f, 0.759386837f, 0.750357985f, 0.741215944f, 0.731964588f, 0.722607553f,
  0.713148773f, 0.703591943f, 0.693941057f, 0.684199929f, 0.674372494f, 0.664462686f,
  0.654474497f, 0.644411862f, 0.634278834f, 0.624079347f, 0.613817513f, 0.603497267f,
  0.593122721f, 0.582697928f, 0.572226822f, 0.561713636f, 0.551162243f, 0.540576756f,
  0.529961288f, 0.519319773f, 0.508656263f, 0.497974843f, 0.487279445f, 0.476574093f,
  0.465862721f, 0.455149323f, 0.444437832f, 0.433732122f, 0.423036128f, 0.412353694f,
  0.401688635f, 0.391044736f, 0.380425841f, 0.369835615f, 0.359277785f, 0.348756015f,
  0.338273942f, 0.327835143f, 0.317443132f, 0.307101458f, 0.296813548f, 0.286582798f,
  0.276412576f, 0.266306221f, 0.256266922f, 0.246297941f, 0.236402407f, 0.226583421f,
  0.216844007f, 0.207187146f, 0.197615787f, 0.188132748f, 0.178740859f, 0.169442832f,
  0.160241365f, 0.151139036f, 0.142138422f, 0.133241966f, 0.124452077f, 0.115771115f,
  0.107201338f, 0.0987449437f, 0.0904040635f, 0.0821807608f, 0.0740770102f, 0.0660947412f,
  0.0582357831f, 0.0505019091f, 0.0428948142f, 0.0354161114f, 0.0280673523f, 0.0208500028f,
  0.0137654608f, 0.00681504514f, 0.0f, -0.0066785058f, -0.0132193789f, -0.0196216013f,
  -0.0258842316f, -0.0320064053f, -0.0379873291f, -0.0438262895f, -0.049522642f, -0.055075828f,
  -0.0604853481f, -0.0657507926f, -0.0708718225f, -0.0758481547f, -0.0806796029f, -0.0853660405f,
  -0.0899074227f, -0.094303757f, -0.0985551402f, -0.102661744f, -0.106623776f, -0.110441558f,
  -0.114115447f, -0.117645875f, -0.121033348f, -0.124278434f, -0.127381757f, -0.130344033f,
  -0.133165985f, -0.135848463f, -0.138392344f, -0.140798554f, -0.143068105f, -0.145202056f,
  -0.147201508f, -0.14906764f, -0.150801688f, -0.152404904f, -0.153878614f, -0.155224234f,
  -0.156443164f, -0.157536879f, -0.158506915f, -0.159354836f, -0.160082251f, -0.160690814f,
  -0.16118224f, -0.161558241f, -0.16182062f, -0.161971167f, -0.162011743f, -0.16194424f,
  -0.161770567f, -0.161492661f, -0.161112517f, -0.160632133f, -0.160053551f, -0.159378827f,
  -0.158610046f, -0.157749325f, -0.15679878f, -0.155760571f, -0.154636875f, -0.153429851f,
  -0.15214172f, -0.150774702f, -0.149331003f, -0.147812888f, -0.146222591f, -0.144562379f,
  -0.142834499f, -0.141041249f, -0.139184892f, -0.137267694f, -0.135291964f, -0.133259952f,
  -0.131173953f, -0.129036233f, -0.12684907f, -0.124614753f, -0.122335508f, -0.12001361f,
  -0.117651299f, -0.115250811f, -0.112814359f, -0.110344172f, -0.107842438f, -0.105311334f,
  -0.102753043f, -0.100169696f, -0.0975634307f, -0.0949363634f, -0.0922905877f, -0.0896281675f,
  -0.0869511515f, -0.0842615739f, -0.0815614238f, -0.0788526908f, -0.0761373118f, -0.0734172165f,
  -0.070694305f, -0.0679704398f, -0.0652474612f, -0.0625271723f, -0.0598113574f, -0.0571017638f,
  -0.0544000976f, -0.0517080501f, -0.0490272641f, -0.0463593528f, -0.043705903f, -0.0410684533f,
  -0.0384485163f, -0.0358475707f, -0.0332670435f, -0.0307083447f, -0.0281728357f, -0.025661841f,
  -0.0231766514f, -0.0207185168f, -0.0182886496f, -0.0158882234f, -0.0135183735f, -0.011180195f,
  -0.00887474511f, -0.0066030426f, -0.00436606444f, -0.00216475036f, 0.0f, 0.00212732656f,
  0.00421640882f, 0.00626646494f, 0.00827675313f, 0.0102465712f, 0.0121752536f, 0.0140621774f,
  0.0159067549f, 0.0177084412f, 0.0194667261f, 0.0211811364f, 0.0228512436f, 0.0244766492f,
  0.0260569975f, 0.0275919642f, 0.0290812701f, 0.0305246618f, 0.0319219306f, 0.0332728997f,
  0.0345774256f, 0.0358354039f, 0.0370467603f, 0.0382114537f, 0.0393294841f, 0.0404008739f,
  0.0414256789f, 0.0424039997f, 0.0433359481f, 0.0442216843f, 0.0450613834f, 0.0458552614f,
  0.0466035567f, 0.0473065376f, 0.0479645021f, 0.0485777669f, 0.0491466857f, 0.049671635f,
  0.0501530059f, 0.0505912267f, 0.0509867445f, 0.0513400286f, 0.0516515709f, 0.051921878f,
  0.0521514937f, 0.0523409657f, 0.0524908677f, 0.0526017919f, 0.0526743457f, 0.0527091585f,
  0.0527068712f, 0.0526681431f, 0.0525936484f, 0.052484069f, 0.0523401126f, 0.0521624908f,
  0.0519519299f, 0.0517091639f, 0.0514349416f, 0.0511300229f, 0.0507951751f, 0.0504311658f,
  0.0500387885f, 0.0496188216f, 0.0491720699f, 0.0486993305f, 0.0482014157f, 0.04767913f,
  0.0471332893f, 0.0465647131f, 0.0459742211f, 0.0453626364f, 0.0447307788f, 0.0440794714f,
  0.0434095412f, 0.0427218042f, 0.0420170836f, 0.0412962027f, 0.0405599698f, 0.0398092009f,
  0.039044708f, 0.0382672921f, 0.0374777541f, 0.0366768949f, 0.0358654931f, 0.0350443423f,
  0.0342142098f, 0.0333758704f, 0.0325300843f, 0.0316776037f, 0.030819172f, 0.0299555268f,
  0.0290873945f, 0.0282154903f, 0.027340522f, 0.0264631826f, 0.0255841613f, 0.0247041285f,
  0.0238237493f, 0.0229436718f, 0.0220645349f, 0.0211869664f, 0.0203115791f, 0.0194389746f,
  0.0185697377f, 0.0177044459f, 0.0168436561f, 0.0159879196f, 0.0151377656f, 0.0142937154f,
  0.0134562738f, 0.0126259299f, 0.0118031614f, 0.0109884273f, 0.0101821767f, 0.0093848398f,
  0.0085968338f, 0.00781856198f, 0.00705041038f, 0.00629275199f, 0.00554594351f, 0.0048103272f,
  0.00408623088f, 0.00337396585f, 0.00267383014f, 0.00198610546f, 0.00131105958f, 0.000648945163f,
  0.0f, -0.000635552628f, -0.0012575041f, -0.00186566007f, -0.00245984085f, -0.00303988089f,
  -0.00360562839f, -0.0041569462f, -0.00469371025f, -0.00521581015f, -0.00572315045f, -0.0062156464f,
  -0.00669322908f, -0.00715584075f, -0.00760343717f, -0.00803598575f, -0.00845346786f, -0.00885587651f,
  -0.0092432145f, -0.00961549859f, -0.00997275766f, -0.010315029f, -0.0106423628f, -0.0109548196f,
  -0.0112524703f, -0.0115353968f, -0.0118036894f, -0.0120574487f, -0.0122967847f, -0.0125218183f,
  -0.0127326762f, -0.0129294964f, -0.013112423f, -0.0132816099f, -0.013437218f, -0.0135794152f,
  -0.0137083782f, -0.0138242887f, -0.0139273368f, -0.0140177179f, -0.0140956333f, -0.0141612906f,
  -0.0142149031f, -0.0142566888f, -0.0142868711f, -0.0143056773f, -0.0143133402f, -0.0143100964f,
  -0.0142961862f, -0.0142718516f, -0.0142373415f, -0.0141929053f, -0.0141387964f, -0.0140752681f,
  -0.0140025802f, -0.0139209917f, -0.0138307633f, -0.0137321576f, -0.0136254383f, -0.0135108717f,
  -0.0133887213f, -0.0132592544f, -0.0131227374f, -0.0129794367f, -0.0128296185f, -0.0126735484f,
  -0.0125114908f, -0.0123437112f, -0.0121704722f, -0.0119920373f, -0.0118086645f, -0.0116206156f,
  -0.0114281457f, -0.0112315118f, -0.0110309655f, -0.0108267581f, -0.0106191384f, -0.0104083512f,
  -0.0101946387f, -0.00997824315f, -0.00975939911f, -0.00953834038f, -0.00931529794f, -0.00909049902f,
  -0.00886416435f, -0.00863651559f, -0.00840776693f, -0.00817813072f, -0.00794781372f, -0.00771702034f,
  -0.00748594943f, -0.00725479564f, -0.00702375034f, -0.00679299841f, -0.00656272285f, -0.00633309968f,
  -0.00610430213f, -0.00587649783f, -0.00564984977f, -0.00542451628f, -0.00520065101f, -0.00497840252f,
  -0.00475791516f, -0.00453932816f, -0.00432277517f, -0.00410838565f, -0.00389628438f, -0.00368659059f,
  -0.00347941928f, -0.00327488035f, -0.00307307835f, -0.00287411385f, -0.00267808186f, -0.00248507294f,
  -0.00229517301f, -0.00210846285f, -0.00192501897f, -0.00174491282f, -0.00156821148f, -0.00139497733f,
  -0.00122526835f, -0.00105913798f, -0.000896635232f, -0.000737804628f, -0.000582686625f, -0.000431317254f,
  -0.000283728499f, -0.000139948155f, 0.0f, 0.000136096147f, 0.000268324366f, 0.00039667252f,
  0.000521132257f, 0.000641698833f, 0.000758371141f, 0.000871151453f, 0.00098004553f, 0.00108506251f,
  0.00118621462f, 0.00128351734f, 0.00137698906f, 0.00146665145f, 0.0015525287f, 0.00163464795f,
  0.001713039f, 0.00178773433f, 0.00185876887f, 0.00192617986f, 0.001990007f, 0.00205029221f,
  0.00210707961f, 0.00216041505f, 0.00221034675f, 0.00225692452f, 0.00230019982f, 0.00234022597f,
  0.00237705815f, 0.00241075247f, 0.0024413669f, 0.00246896036f, 0.00249359314f, 0.00251532672f,
  0.00253422372f, 0.00255034771f, 0.00256376271f, 0.00257453392f, 0.00258272723f, 0.00258840923f,
  0.00259164697f, 0.00259250775f, 0.00259105954f, 0.00258737057f, 0.00258150953f, 0.00257354509f,
  0.00256354548f, 0.00255158008f, 0.00253771734f, 0.00252202619f, 0.00250457507f, 0.00248543196f,
  0.00246466533f, 0.00244234246f, 0.00241853087f, 0.00239329739f, 0.00236670813f, 0.00233882875f,
  0.00230972469f, 0.00227946043f, 0.00224809931f, 0.00221570488f, 0.00218233909f, 0.00214806339f,
  0.00211293809f, 0.00207702327f, 0.00204037712f, 0.00200305786f, 0.0019651216f, 0.00192662445f,
  0.00188762078f, 0.00184816413f, 0.00180830702f, 0.00176810054f, 0.00172759476f, 0.0016868388f,
  0.00164588005f, 0.00160476542f, 0.00156353984f, 0.00152224756f, 0.0014809313f, 0.00143963262f,
  0.00139839191f, 0.00135724794f, 0.00131623878f, 0.00127540051f, 0.00123476866f, 0.00119437685f,
  0.0011542578f, 0.00111444294f, 0.00107496232f, 0.00103584467f, 0.000997117488f, 0.000958807184f,
  0.000920938735f, 0.000883535948f, 0.000846621406f, 0.000810216472f, 0.000774341286f, 0.000739014824f,
  0.000704254897f, 0.000670078152f, 0.000636500015f, 0.00060353498f, 0.000571196142f, 0.000539495843f,
  0.000508445024f, 0.000478053844f, 0.000448331266f, 0.000419285352f, 0.000390923058f, 0.000363250467f,
  0.0003362727f, 0.00030999392f, 0.000284417416f, 0.000259545661f, 0.000235380154f, 0.000211921681f,
  0.000189170154f, 0.00016712473f, 0.000145783837f, 0.000125145161f, 0.000105205654f, 8.59616266e-05f,
  6.7408735e-05f, 4.95419954e-05f, 3.23558234e-05f, 1.58440616e-05f, 0.0f, -1.51835975e-05f,
  -2.97144725e-05f, -4.36008377e-05f, -5.68513678e-05f, -6.94751579e-05f, -8.14817176e-05f, -9.28809241e-05f,
  -0.000103683014f, -0.000113898568f, -0.00012353847f, -0.000132613903f, -0.00014113629f, -0.000149117302f,
  -0.000156568873f, -0.000163503093f, -0.000169932246f, -0.000175868758f, -0.000181325231f, -0.00018631437f,
  -0.000190848965f, -0.000194941909f, -0.000198606125f, -0.000201854637f, -0.000204700453f, -0.000207156598f,
  -0.00020923611f, -0.000210951985f, -0.000212317202f, -0.000213344698f, -0.000214047293f, -0.000214437809f,
  -0.000214528889f, -0.000214333151f, -0.000213863037f, -0.000213130901f, -0.000212148938f, -0.000210929182f,
  -0.000209483551f, -0.000207823745f, -0.000205961318f, -0.000203907621f, -0.0002016738f, -0.000199270842f,
  -0.000196709487f, -0.000194000255f, -0.000191153464f, -0.000188179212f, -0.000185087352f, -0.000181887473f,
  -0.000178588976f, -0.00017520097f, -0.000171732361f, -0.000168191764f, -0.000164587545f, -0.000160927855f,
  -0.000157220536f, -0.0001534732f, -0.000149693209f, -0.000145887621f, -0.000142063305f, -0.000138226795f,
  -0.00013438442f, -0.000130542234f, -0.000126706029f, -0.000122881349f, -0.000119073477f, -0.000115287461f,
  -0.00011152809f, -0.000107799904f, -0.00010410721f, -0.000100454061f, -9.68442837e-05f, -9.32814728e-05f,
  -8.9768997e-05f, -8.63099849e-05f, -8.29073542e-05f, -7.95638116e-05f, -7.62818381e-05f, -7.30637257e-05f,
  -6.99115481e-05f, -6.68271823e-05f, -6.38123165e-05f, -6.08684568e-05f, -5.79969201e-05f, -5.51988451e-05f,
  -5.24751995e-05f, -4.98267909e-05f, -4.72542561e-05f, -4.4758086e-05f, -4.23386155e-05f, -3.99960336e-05f,
  -3.77303986e-05f, -3.55416269e-05f, -3.34295182e-05f, -3.13937344e-05f, -2.9433837e-05f, -2.75492675e-05f,
  -2.57393622e-05f, -2.40033642e-05f, -2.23404131e-05f, -2.07495668e-05f, -1.92297957e-05f, -1.7779992e-05f,
  -1.63989771e-05f, -1.50855003e-05f, -1.38382493e-05f, -1.26558562e-05f, -1.15368948e-05f, -1.04798937e-05f,
  -9.48333673e-06f, -8.54566679e-06f, -7.66529411e-06f, -6.84059614e-06f, -6.06992489e-06f, -5.35160962e-06f,
  -4.68396092e-06f, -4.06527488e-06f, -3.49383731e-06f, -2.96792632e-06f, -2.48581591e-06f, -2.04578055e-06f,
  -1.64609696e-06f, -1.28504792e-06f, -9.60925149e-07f, -6.72032229e-07f, -4.16687101e-07f, -1.93224849e-07f,
  0.0f,
};

/* The half-band's non-zero side taps, outermost first: 0.5 sinc(m / 2) x
 * Kaiser(m, beta 9.5) at the odd offsets m = 33, 31 .. 1 from the centre tap
 * (0.5), scaled to sum to 0.25 (unity gain at DC, zero at Nyquist). */
static const float fm1_resampler_halfband[FM1_RESAMPLER_HB_PAIRS] = {
  5.50093318e-06f, -3.5275516e-05f, 0.000112705551f, -0.000277392974f,
  0.000586701324f, -0.00111883786f, 0.00197581365f, -0.00328717008f,
  0.00521668373f, -0.00797689427f, 0.0118621085f, -0.0173253156f,
  0.0251681972f, -0.0370691828f, 0.0573912486f, -0.102228932f,
  0.317000031f,
};

typedef struct fm1_resampler {
  int64_t step;       /* input samples per intermediate sample, 32.32 fixed point */
  int64_t lead;       /* step + the kernel's reach + 1: input an output needs past rel */
  int64_t rel;        /* next intermediate sample's input position less the inputs
                         received so far, 32.32 (at or below zero once fed) */
  uint32_t tap_step;  /* kernel table entries per input sample, 16.16 */
  float gain;         /* intermediate samples per input sample (rho) */
  uint32_t mode;      /* FM1_RESAMPLER_OFF, _PASS or _CONVERT */
  uint32_t held;      /* pass-through: in[0] holds a sample not yet popped */
  uint32_t in_w, side_w, centre_w;   /* next write slot of each ring */
  /* Rings, each written twice (at w and w + CAP) so any window of CAP
   * consecutive samples is contiguous. */
  float in[2 * FM1_RESAMPLER_IN_CAP];
  float side[2 * FM1_RESAMPLER_SIDE_CAP];      /* intermediate samples 2k + 1 */
  float centre[2 * FM1_RESAMPLER_CENTRE_CAP];  /* intermediate samples 2k */
} fm1_resampler_t;

/* Sets r up to convert in_rate to out_rate. Returns 1, or 0 (r then passes
 * nothing: needed() is 0 and pop() returns 0) when the ratio
 * in_rate / out_rate is outside 1..FM1_RESAMPLER_MAX_RATIO or either rate is
 * not a positive finite number. */
static inline int fm1_resampler_init(fm1_resampler_t *r, float in_rate, float out_rate) {
  uint32_t i;
  double ratio, rho;
  r->step = r->lead = r->rel = 0;
  r->tap_step = 0;
  r->gain = 0.0f;
  r->mode = FM1_RESAMPLER_OFF;
  r->held = 0;
  r->in_w = r->side_w = r->centre_w = 0;
  for (i = 0; i < 2 * FM1_RESAMPLER_IN_CAP; ++i) r->in[i] = 0.0f;
  for (i = 0; i < 2 * FM1_RESAMPLER_SIDE_CAP; ++i) r->side[i] = 0.0f;
  for (i = 0; i < 2 * FM1_RESAMPLER_CENTRE_CAP; ++i) r->centre[i] = 0.0f;
  if (!(in_rate > 0.0f && out_rate > 0.0f && in_rate < 1e30f && out_rate < 1e30f)) return 0;
  ratio = (double)in_rate / (double)out_rate;
  if (in_rate == out_rate) {
    r->mode = FM1_RESAMPLER_PASS;
    return 1;
  }
  if (!(ratio >= 1.0 && ratio <= FM1_RESAMPLER_MAX_RATIO)) return 0;
  rho = 2.0 / ratio;                 /* in [0.5, 2] */
  r->mode = FM1_RESAMPLER_CONVERT;
  r->gain = (float)rho;
  r->step = (int64_t)(ratio / 2.0 * 4294967296.0 + 0.5);
  r->tap_step = (uint32_t)(rho * FM1_RESAMPLER_PHASES * 65536.0 + 0.5);
  /* The kernel reaches SPAN / 2 intermediate samples, SPAN / (2 rho) input
   * samples, either side; one input more covers the rounding of tap_step. */
  r->lead = r->step + (int64_t)(FM1_RESAMPLER_SPAN / (2.0 * rho) * 4294967296.0 + 0.5) +
            ((int64_t)1 << 32);
  return 1;
}

/* Input samples r must receive before the next fm1_resampler_pop. */
static inline uint32_t fm1_resampler_needed(const fm1_resampler_t *r) {
  int64_t v;
  if (r->mode != FM1_RESAMPLER_CONVERT) return r->mode == FM1_RESAMPLER_PASS && !r->held;
  v = r->rel + r->lead;
  return v > 0 ? (uint32_t)(((uint64_t)v + 0xFFFFFFFFu) >> 32) : 0u;
}

/* Takes up to n samples, never more than fm1_resampler_needed(r); returns
 * how many it took. */
static inline uint32_t fm1_resampler_push(fm1_resampler_t *r, const float *in, uint32_t n) {
  uint32_t i, need = fm1_resampler_needed(r);
  if (n > need) n = need;
  if (r->mode != FM1_RESAMPLER_CONVERT) {
    if (n) { r->in[0] = in[0]; r->held = 1; }
    return n;
  }
  for (i = 0; i < n; ++i) {
    r->in[r->in_w] = r->in[r->in_w + FM1_RESAMPLER_IN_CAP] = in[i];
    if (++r->in_w == FM1_RESAMPLER_IN_CAP) r->in_w = 0;
  }
  r->rel -= (int64_t)n << 32;
  return n;
}

/* The kernel at table position t (16.16), linearly interpolated. */
static inline float fm1_resampler_tap_(uint32_t t) {
  const float *k = &fm1_resampler_kernel[t >> 16];
  return k[0] + (float)(t & 0xFFFFu) * (1.0f / 65536.0f) * (k[1] - k[0]);
}

/* One intermediate sample at input position rel (relative to the inputs
 * received): the sum of x[n] k((P - n) rho) over the inputs the kernel
 * reaches. The taps at or before P walk the half table outwards one way,
 * the later ones the other; two sums, so the two chains overlap. */
static inline float fm1_resampler_intermediate_(fm1_resampler_t *r) {
  const uint32_t ts = r->tap_step;
  const uint32_t end = (uint32_t)(FM1_RESAMPLER_KERNEL_LEN - 1) << 16;
  const int64_t rel = r->rel;
  const uint32_t frac = (uint32_t)((uint64_t)rel & 0xFFFFFFFFu);
  /* The input at floor(P): the newest input is at in_w - 1 + CAP. */
  const float *before = &r->in[r->in_w + FM1_RESAMPLER_IN_CAP - 1] + (rel >> 32) + 1;
  const float *after = before + 1;
  uint32_t tb = (uint32_t)(((uint64_t)frac * ts) >> 32);
  uint32_t ta = (uint32_t)((((uint64_t)1 << 32) - frac) * ts >> 32);
  float sb = 0.0f, sa = 0.0f;
  for (; tb < end && ta < end; tb += ts, ta += ts, --before, ++after) {
    sb += fm1_resampler_tap_(tb) * *before;
    sa += fm1_resampler_tap_(ta) * *after;
  }
  for (; tb < end; tb += ts, --before) sb += fm1_resampler_tap_(tb) * *before;
  for (; ta < end; ta += ts, ++after) sa += fm1_resampler_tap_(ta) * *after;
  r->rel = rel + r->step;
  return (sb + sa) * r->gain;
}

/* The next output sample. Returns 0 and changes nothing if r still needs
 * input (fm1_resampler_needed > 0). */
static inline float fm1_resampler_pop(fm1_resampler_t *r) {
  const float *e;
  float a, b, y0 = 0.0f, y1 = 0.0f;
  uint32_t j;
  if (r->mode != FM1_RESAMPLER_CONVERT) {
    if (!r->held) return 0.0f;
    r->held = 0;
    return r->in[0];
  }
  if (fm1_resampler_needed(r)) return 0.0f;
  a = fm1_resampler_intermediate_(r);   /* intermediate sample 2k */
  b = fm1_resampler_intermediate_(r);   /* 2k + 1 */
  r->centre[r->centre_w] = r->centre[r->centre_w + FM1_RESAMPLER_CENTRE_CAP] = a;
  if (++r->centre_w == FM1_RESAMPLER_CENTRE_CAP) r->centre_w = 0;
  r->side[r->side_w] = r->side[r->side_w + FM1_RESAMPLER_SIDE_CAP] = b;
  if (++r->side_w == FM1_RESAMPLER_SIDE_CAP) r->side_w = 0;
  /* Output k is the half-band centred on intermediate sample 2k - 32: the
   * centre tap on it (the oldest in its ring), the side taps on the odd
   * samples 2k - 65 .. 2k + 1 (all of theirs), paired from the outside in. */
  e = &r->side[r->side_w];
  for (j = 0; j + 1 < FM1_RESAMPLER_HB_PAIRS; j += 2) {
    y0 += fm1_resampler_halfband[j] * (e[j] + e[FM1_RESAMPLER_SIDE_CAP - 1 - j]);
    y1 += fm1_resampler_halfband[j + 1] * (e[j + 1] + e[FM1_RESAMPLER_SIDE_CAP - 2 - j]);
  }
  for (; j < FM1_RESAMPLER_HB_PAIRS; ++j) {
    y0 += fm1_resampler_halfband[j] * (e[j] + e[FM1_RESAMPLER_SIDE_CAP - 1 - j]);
  }
  return (y0 + y1) + 0.5f * r->centre[r->centre_w];
}

/* Array form: takes inputs from in[0..n_in) as outputs need them and writes
 * up to max_out outputs; returns how many it wrote, and stores how many
 * inputs it took in *n_used (when not NULL). Stops early when the input runs
 * out; what it took is kept for the next call. */
static inline uint32_t fm1_resampler_process(fm1_resampler_t *r, const float *in, uint32_t n_in,
                                             uint32_t *n_used, float *out, uint32_t max_out) {
  uint32_t used = 0, made = 0;
  while (made < max_out) {
    if (used < n_in) used += fm1_resampler_push(r, in + used, n_in - used);
    if (fm1_resampler_needed(r)) break;
    out[made++] = fm1_resampler_pop(r);
  }
  if (n_used) *n_used = used;
  return made;
}

/* Group delay in output samples: 0 for pass-through, else HB_K = 16
 * (output k is the signal at input time (k - 16) / out_rate; input 0 is
 * time 0). */
static inline float fm1_resampler_delay(const fm1_resampler_t *r) {
  return r->mode == FM1_RESAMPLER_CONVERT ? (float)FM1_RESAMPLER_HB_K : 0.0f;
}

#endif /* FM1_RESAMPLER_H_ */
